window.DMA={
  weeks:[{id:'week1',n:'01',title:['营销基础、数据与归因','Foundations, data & attribution'],intro:['先明确营销目标与旅程阶段，再选择数据、指标和归因方式。','Define the marketing objective and journey stage before choosing data, metrics and attribution.'],source:'w1',concepts:[
    {title:['数字营销的特殊性','What makes digital marketing distinct'],items:[['个性化让不同消费者获得不同信息。','Personalization enables different messages for different consumers.'],['用户生成内容让消费者也参与品牌传播。','User-generated content makes consumers active participants in brand communication.']]},
    {title:['Paid · Owned · Earned · Category','Media and touchpoint classification'],items:[['Paid：广告、付费搜索、付费 influencer。','Paid: advertising, sponsored search and paid influencers.'],['Owned：品牌官网、App、品牌自有内容。','Owned: brand websites, apps and brand-controlled content.'],['Earned：评论、转发与消费者口碑，也可能为负面。','Earned: reviews, sharing and consumer word of mouth, including negative responses.'],['Category：竞争对手及独立行业内容。','Category: competitor and independent category content.']]},
    {title:['数据结构与来源','Data structure and sources'],items:[['Structured：点击、销售额、session time。Unstructured：文本、图片、视频。','Structured: clicks, sales and session time. Unstructured: text, images and video.'],['On-site 是网页可见内容；clickstream 是用户的行为记录。','On-site data describe visible page content; clickstream data describe user actions.'],['Zero / first / second / third party 区分主动提供、自有收集、伙伴共享及外部获取。','Zero / first / second / third party distinguish volunteered data, direct collection, partner sharing and external sourcing.']]},
    {title:['指标与目标','Metrics follow objectives'],items:[['RACE：Reach、Act、Convert、Engage。每个阶段需要不同 KPI。','RACE: Reach, Act, Convert and Engage. Each stage needs different KPIs.'],['展示不等于看见；点击不等于商业成果。','An impression does not guarantee attention; a click does not guarantee a business outcome.'],['Bounce rate 要结合用户任务与平台口径解释。','Interpret bounce rate using the visitor’s task and the platform’s definition.']]},
    {title:['规则型归因','Rule-based attribution'],items:[['First-click 奖励引入，last-click 奖励收尾，linear 平均分配。','First-click rewards initiation, last-click rewards closing and linear distributes credit equally.'],['Position-based 强调起点和终点，time-decay 强调近期接触。','Position-based emphasizes the first and last touches; time-decay emphasizes recent touches.']]},
    {title:['数据驱动归因','Data-driven attribution'],items:[['模型利用转化与未转化路径估计触点贡献。','Models use converted and non-converted journeys to estimate touchpoint contributions.'],['信用分配受模型、窗口、可见触点和识别能力影响。','Credit allocation depends on the model, window, observable touches and identity resolution.']],takeaway:['归因 credit 与 causal effect 应分开解释。','Interpret attribution credit separately from causal effect.']}
  ]}],
  tutorials:[],sources:[],review:[]
};

DMA.weeks.push(
{id:'week2',n:'02',title:['归因挑战、全渠道与社交媒体','Attribution challenges, omnichannel & social media'],intro:['渠道有不同的角色，也会跨时间、设备和平台相互影响。','Channels play different roles and interact across time, devices and platforms.'],source:'w2',concepts:[
 {title:['触点角色与顺序','Touchpoint roles & sequence'],items:[['Introduction、assist、conversion 是不同角色。渠道贡献取决于 WHEN 和 HOW。','Introduction, assist and conversion are distinct roles. A channel’s contribution depends on WHEN and HOW it is used.'],['只判断触点有没有出现，会遗漏出现位置和时机。','Recording only whether a touch occurred loses position and timing information.']]},
 {title:['时间窗口与身份识别','Time windows & identity'],items:[['窗口太短可能把延迟购买当成未转化；太长也会改变 credit。','A short window can label a delayed purchase as a non-conversion; a longer window also changes credit.'],['多设备、多平台和隐私限制使完整 journey 难以观察。','Multiple devices, platforms and privacy restrictions make complete journeys difficult to observe.']],takeaway:['根据销售周期解释窗口，不存在一个适合所有行业的长度。','Interpret windows in relation to the sales cycle; no single length fits every industry.']},
 {title:['View-through 与增量','View-through & incrementality'],items:[['消费者可能看见广告，但没有点击，随后仍然购买。','A consumer may see an ad without clicking and later purchase.'],['用广告组与对照组比较 conversion，可研究非点击曝光的影响。','Compare conversion in exposed and control groups to study the impact of non-click exposure.']],takeaway:['观察到曝光后的购买，还需要验证广告是否带来额外购买。','A purchase after exposure still requires evidence that the ad created an additional purchase.']},
 {title:['Marketing Mix Modeling','营销组合模型'],items:[['使用聚合数据连接销售与媒体投入、促销、季节、天气等因素。','Use aggregate data to relate sales to media investment, promotions, seasonality, weather and other factors.'],['适合跨媒体和较长期的预算问题，可纳入线上归因难以捕捉的因素。','Suited to cross-media and longer-term budget questions, including factors difficult to capture in online attribution.'],['个体旅程细节较少，结果依赖模型和可用变化。','Provides less individual journey detail; results depend on the model and available variation.']]},
 {title:['全渠道与跨渠道影响','Omnichannel & cross-channel effects'],items:[['Multichannel 是多个渠道并存；omnichannel 强调连接与协同体验。','Multichannel means multiple channels coexist; omnichannel emphasizes connected, coordinated experiences.'],['Carryover：影响延续到未来。Spillover：一个渠道影响另一个渠道。','Carryover: an effect persists into the future. Spillover: one channel affects another.'],['Webrooming 是线上研究、线下购买；showrooming 是线下体验、线上购买。','Webrooming combines online research with offline purchase; showrooming combines offline inspection with online purchase.']]},
 {title:['Influence 与 virality','影响力与传播'],items:[['Influencer 价值取决于 followers 的网络深度，以及各层的 activation 和 sharing 概率。','Influencer value depends on network depth and the activation and sharing probabilities at each level.'],['高唤醒情绪如 awe、anger、anxiety 可以促进传播。正向情绪、故事和 surprise 也重要。','High-arousal emotions such as awe, anger and anxiety can promote sharing. Positive emotion, narrative and surprise also matter.'],['传播内容应与品牌身份及目标相连，不能只追求热度。','Connect shareable content to brand identity and objectives rather than focusing solely on popularity.']]},
 {title:['社交媒体指标与模型','Social metrics & modeling'],items:[['Conversation、amplification、applause 和 share of voice 对应不同反应。','Conversation, amplification, applause and share of voice capture different responses.'],['Likes、shares、comments 可以分别作为 Y；内容形式、时间、平台等作为 X。','Likes, shares and comments can be separate outcomes; format, timing and platform can be predictors.'],['不同 engagement outcome 可能需要不同内容策略。','Different engagement outcomes may require different content strategies.']]},
 {title:['非结构化与多模态数据','Unstructured & multimodal data'],items:[['文本、图片和视频同时包含多个信息维度，需要先提取可分析的特征。','Text, images and video contain several simultaneous dimensions; extract analyzable features first.'],['图片特征包括颜色、亮度、对比度、复杂度和人物；视频也可以识别动作和事件。','Image features include color, brightness, contrast, complexity and people; video can also encode actions and events.'],['可整合 text、image、tags 与 behavioral outcome，再分析其关系。','Combine text, image, tags and behavioral outcomes before analyzing their relationships.']]}
],visual:{title:['跨渠道旅程','A cross-channel journey'],steps:[['社交媒体认知','Social awareness'],['手机搜索','Mobile search'],['店内体验','In-store inspection'],['电脑购买','Desktop purchase'],['评论与复购','Review & repeat']],note:['教学示意：最后完成购买的渠道，只记录了旅程的一部分。','Teaching illustration: the channel closing the purchase captures only part of the journey.']}}
,
{id:'week3',n:'03',title:['文本分析、Emoji 与生成式 AI','Text analytics, emojis & generative AI'],intro:['把消费者表达转化为 sentiment、topic 和内容特征，再连接营销结果。','Turn consumer expression into sentiment, topics and content features, then relate these to marketing outcomes.'],source:'w3',concepts:[
 {title:['情感分析的多个维度','Dimensions of sentiment'],items:[['Valence：正面还是负面。Extremity：表达的强度。','Valence: positive versus negative. Extremity: intensity of expression.'],['Subjectivity / emotionality：观点与情绪相对于事实的程度。','Subjectivity / emotionality: the extent of opinion and emotion relative to factual content.'],['具体 emotion 可区分 anger、fear、hope、excitement，超越正负二分。','Specific emotions distinguish anger, fear, hope and excitement beyond a positive/negative split.']],takeaway:['课件有时用 polarity 表示 extremity；TextBlob 用 polarity 表示有方向的 sentiment score。解释时应查对应工具的定义。','The slides sometimes use polarity for extremity; TextBlob uses polarity for a signed sentiment score. Check the definition for the specific tool.']},
 {title:['Topic 与 sentiment 的组合','Combining topics & sentiment'],items:[['Topic analysis 回答“消费者在讨论什么”；sentiment 回答“如何评价”。','Topic analysis asks what consumers discuss; sentiment asks how they evaluate it.'],['把 topic 与 journey stage 结合，可识别具体 pleasure / pain points。','Combine topics with journey stages to identify specific pleasure and pain points.'],['主题频率与负面情绪可帮助确定服务改善的优先级。','Topic frequency and negative sentiment can help prioritize service improvements.']]},
 {title:['语言如何影响 engagement','Language & engagement'],items:[['情绪唤醒、concreteness、familiarity、readability 和 simplicity 都可能与注意和互动有关。','Emotional arousal, concreteness, familiarity, readability and simplicity can relate to attention and engagement.'],['将 NLP 特征作为 X，将阅读、互动等结果作为 Y，检验关系。','Use NLP features as predictors and reading or engagement measures as outcomes to examine relationships.']]},
 {title:['Textual paralanguage','文字中的非语言线索'],items:[['Emoji、emoticon、重复字符、标点和非标准拼写都能补充语气。','Emojis, emoticons, repeated characters, punctuation and non-standard spelling can convey tone.'],['PARA 可以把相关线索转换为可分析的指标。','PARA can convert these cues into analyzable measures.'],['特征效果需要结合品牌、受众与 communication context 理解。','Interpret feature effects in relation to brand, audience and communication context.']]},
 {title:['Emoji 的含义与边界','Emoji meaning & boundary conditions'],items:[['Iconic 直接代表物体；symbolic 代表需要理解的抽象意义。','Iconic use depicts an object directly; symbolic use requires interpretation of an abstract meaning.'],['Emoji 可补充文字，也可替代文字。组合方式影响 processing fluency。','Emojis can supplement or substitute for text. Their composition affects processing fluency.'],['多个替代性 emoji 可能降低可读性；高端品牌也需考虑 perceived competence。','Multiple substitutive emojis may reduce fluency; premium brands should also consider perceived competence.']]},
 {title:['多模态情绪','Multimodal emotion'],items:[['Text、emoji、image 可提供互补信息。','Text, emojis and images can provide complementary information.'],['Emoji 的意义依赖文字语境；独立分析可能遗漏含义。','Emoji meaning depends on textual context; separate analysis may miss the intended meaning.']]},
 {title:['GenAI 与 prompt','Generative AI & prompting'],items:[['可用于内容、关键词构思、文本分类、客户服务及个性化沟通。','Applications include content, keyword ideation, text classification, customer service and personalized communication.'],['Prompt 可包含 instruction、context、input data 和 output format。','A prompt can specify instructions, context, input data and output format.'],['复杂任务可拆分为步骤，并明确质量标准和人工审阅。','Break complex tasks into steps and specify quality standards and human review.'],['Hallucination、bias 和隐私问题会影响使用质量。','Hallucination, bias and privacy issues affect quality of use.']]}
],visual:{title:['文本如何进入营销模型','How text enters a marketing model'],steps:[['原始表达','Raw expression'],['语境与清理','Context & preparation'],['提取特征','Extract features'],['连接结果','Link outcomes'],['解释与改进','Interpret & improve']],note:['例如：从帖子提取 emotion / topic，控制平台和品牌差异后分析 engagement。此处为流程示意。','For example, extract emotions and topics from posts, then examine engagement while accounting for platform and brand differences. This is a process illustration.']}}
,
{id:'week4',n:'04',title:['评论、评分与搜索营销','Reviews, ratings & search marketing'],intro:['理解消费者评价的结构，并区分 organic 与 paid search 的作用。','Understand the structure of consumer evaluations and distinguish the roles of organic and paid search.'],source:'w4',concepts:[
 {title:['Ratings 与 reviews','评分与文字评论'],items:[['Rating 通常是数字或符号；review 是文本，包含体验、感受与解释。','Ratings are usually numeric or symbolic; reviews are text containing experiences, feelings and explanations.'],['同一分值的含义依赖平台、分布和用户群体。','The meaning of a score depends on the platform, distribution and user population.'],['自动 sentiment 与 star rating 可能因语境、比较和词典局限而不一致。','Automated sentiment can diverge from star ratings because of context, comparisons and lexicon limitations.']]},
 {title:['评论存在与可信度','Review presence & credibility'],items:[['课件研究显示，评论的存在本身能影响 purchase likelihood。','The studies summarized in the slides show that the presence of reviews can affect purchase likelihood.'],['“Too good to be true” 提醒：极高评分也可能引起怀疑。','The “too good to be true” effect suggests that extremely positive ratings can create skepticism.'],['研究中出现的评分最优区间是情境发现，不是通用目标。','An optimal rating range found in a study is context-specific, not a universal target.']]},
 {title:['Review helpfulness','评论有用性'],items:[['Argument quality、clarity、comprehensiveness 和 relevance 比单纯长度更有解释价值。','Argument quality, clarity, comprehensiveness and relevance can be more informative than length alone.'],['Review images 的效果受产品类型、reviewer reputation、rating 和 context fit 调节。','Effects of review images depend on product type, reviewer reputation, rating and context fit.'],['展示产品实际应用的图片，在相关情境中更有帮助。','Images showing a product in use can be more helpful in the relevant contexts.']]},
 {title:['评分呈现与企业回应','Rating presentation & firm response'],items:[['Star / symbol 与纯数字的呈现会影响 perceived magnitude，尤其在中间分值。','Stars or symbols versus numbers can affect perceived magnitude, especially around midpoint ratings.'],['持续回应与 response speed 可以促进后续 review volume。','Responsiveness and response speed can increase subsequent review volume.'],['课件研究中，response length 没有同样显著的影响。','In the study presented, response length did not show the same significant effect.']]},
 {title:['Search intent 与 keywords','搜索意图与关键词'],items:[['Search 由消费者主动发起；关键词具体程度帮助判断 journey stage。','Consumers initiate search; keyword specificity helps indicate the journey stage.'],['Crawling、indexing、serving 是课件介绍的基本搜索流程。','Crawling, indexing and serving are the basic search stages introduced in the slides.'],['搜索行为可以提供 demand 与 sales 的预测信号。','Search behavior can provide predictive signals for demand and sales.']]},
 {title:['SEO','搜索引擎优化'],items:[['On-page：内容相关性、标题、heading、keyword 和 meta 信息。','On-page: content relevance, titles, headings, keywords and metadata.'],['Off-page：链接、authority 及外部信号。','Off-page: links, authority and external signals.'],['课件用 RankBrain、CTR、dwell time 和 pogo-sticking 解释 search intent 与用户满意度。','The slides use RankBrain, CTR, dwell time and pogo-sticking to discuss search intent and satisfaction.']],takeaway:['这里保留课件的机制框架，不能据此断言每个指标都是当前直接 ranking factor。','This preserves the conceptual framework in the slides; it does not establish every measure as a current direct ranking factor.']},
 {title:['SEA','搜索引擎广告'],items:[['Paid / sponsored search 的位置与 bid、Quality Score、ad extensions 有关。','Paid or sponsored search position relates to bids, Quality Score and ad extensions.'],['Quality Score 也与 CPC 相关。','Quality Score also relates to CPC.'],['未点击的广告也可能影响 awareness 和 brand image。','An unclicked ad may still affect awareness and brand image.']]},
 {title:['SEO 与 SEA 协同','SEO & SEA together'],items:[['SEO 通常需要更长投入周期；SEA 可提供较即时的战术曝光。','SEO generally needs a longer investment horizon; SEA can provide more immediate tactical exposure.'],['具体、低流量关键词可能反映更接近购买的 search intent。','Specific, less popular keywords may indicate search intent closer to purchase.'],['按时间目标、意图与最终价值配置两者。','Allocate both according to time horizon, intent and eventual value.']]}
]}
,
{id:'week5',n:'05',title:['广告定价、个性化与实验','Ad pricing, personalization & experiments'],intro:['区分计费基础、竞价机制与定向方式，理解优化行动如何被验证。','Distinguish billing bases, auction mechanisms and targeting approaches, then consider how to validate an optimization.'],source:'w5',concepts:[
 {title:['CPM / CPC / CPA','计费基础'],items:[['CPM 按千次展示；CPC 按点击；CPA 按定义的 acquisition / conversion 计费。','CPM charges per thousand impressions; CPC per click; CPA per defined acquisition or conversion.'],['Awareness、traffic 与 conversion 目标会改变合适的计费选择。','Awareness, traffic and conversion objectives change which billing basis is appropriate.'],['CPM 中 advertiser 承担较多结果风险；CPA 中 publisher 承担较多。','Advertisers bear more outcome risk under CPM; publishers bear more under CPA.']]},
 {title:['RTB 与 second-price auction','实时竞价与第二价格拍卖'],items:[['CPM / CPC / CPA 是计费基础；RTB 是价格形成机制。','CPM, CPC and CPA are billing bases; RTB is a mechanism for determining price.'],['简化 second-price auction：最高出价者获胜，按第二高出价支付。','In a simplified second-price auction, the highest bidder wins and pays the second-highest bid.'],['真实广告拍卖还会包含质量等条件，不能机械套用简化模型。','Actual advertising auctions can include quality and other conditions; the simplified model is not a complete platform specification.']]},
 {title:['Segment 与 one-to-one','个性化层级'],items:[['Segment targeting 对一组相似客户使用相同信息。','Segment targeting uses the same message for a group of similar customers.'],['One-to-one 结合个人历史、兴趣、位置等定制信息。','One-to-one targeting tailors messages using individual history, interests, location and other information.'],['细粒度个性化需要额外数据、内容和技术资源。','Fine-grained personalization requires additional data, content and technical resources.']]},
 {title:['Targeting 类型','Types of targeting'],items:[['Contextual 基于页面内容；behavioral 基于用户的搜索和行为。','Contextual targeting uses page content; behavioral targeting uses a user’s search and behavior.'],['Retargeting 针对曾经接触品牌的人；geographic 针对位置。','Retargeting reaches prior brand visitors; geographic targeting uses location.'],['Dynamic targeting 实时组合多种信号。','Dynamic targeting combines multiple signals in real time.']]},
 {title:['A/B testing','随机实验'],items:[['把可比较人群随机分到 control 与 variant，比较结果。','Randomly assign comparable users to control and variant groups, then compare outcomes.'],['Randomization 平衡其他影响因素，帮助识别改变的增量影响。','Randomization balances other influences and helps identify the incremental effect of a change.'],['预先明确假设、primary KPI、样本与观察窗口。','Specify the hypothesis, primary KPI, sample and observation window in advance.']],takeaway:['显著性、效果大小与实际商业价值需要一起解释。','Interpret statistical significance, effect size and practical business value together.']},
 {title:['Retargeting 的时机','Retargeting timing'],items:[['课件中的购物车研究发现：弃购后 30–60 分钟的过早提醒可能降低购买。','The cart study in the slides finds that early reminders within 30–60 minutes of abandonment can reduce purchase.'],['效果取决于消费者此前的行为、需求状态及信息具体程度。','Effectiveness depends on prior behavior, need state and information specificity.'],['“曾经访问”不足以证明“需要立即提醒”。','A prior visit alone does not establish a need for an immediate reminder.']]},
 {title:['正向情绪与搜索','Positive emotion during search'],items:[['Incidental positive emotion 可以影响 keyword choice 和 sponsored click probability。','Incidental positive emotion can influence keyword choice and sponsored click probability.'],['研究机制包括 persuasion knowledge 的激活减少。','The proposed mechanism includes reduced activation of persuasion knowledge.'],['将情绪、产品类型和使用情境作为需要验证的条件。','Treat emotion, product type and usage context as conditions to validate.']]}
]}
,
{id:'week6',n:'06',title:['推荐系统、移动与位置营销','Recommenders, mobile & location marketing'],intro:['推荐和移动渠道影响整条旅程，应同时观察转化、长期价值与跨渠道结果。','Recommendations and mobile channels affect the full journey; examine conversion, long-term value and cross-channel outcomes together.'],source:'w6',concepts:[
 {title:['Content-based filtering','基于内容的推荐'],items:[['根据 item 属性及相似性推荐产品。','Recommend products using item attributes and similarity.'],['可在行为数据较少时利用 item 信息。','Item information can help when behavioral data are limited.'],['“相似”的定义可能错过用户真正喜欢的属性。','A predefined notion of similarity may miss the attributes a user actually values.']]},
 {title:['Collaborative 与 hybrid','协同过滤与混合推荐'],items:[['Collaborative：根据相似用户的评价、浏览或购买行为。','Collaborative: use ratings, views or purchases from similar users.'],['主要问题是 sparsity、cold start 与计算负担。','Key problems include sparsity, cold start and computational burden.'],['Hybrid / meta-path 将行为、属性和关系结合。','Hybrid or meta-path approaches combine behavior, attributes and relationships.']]},
 {title:['Framing 与 AI / human','推荐呈现与推荐者'],items:[['相同建议采用 user-based framing，可能提高某些用户的 CTR。','The same recommendation with user-based framing can raise CTR for some users.'],['效果受用户经验、产品吸引力和 perceived similarity 调节。','Effects depend on user experience, product attractiveness and perceived similarity.'],['Utilitarian 情境可能偏好 AI 的能力；hedonic 情境可能更重视 human judgment。','Utilitarian contexts may favor perceived AI competence; hedonic contexts may favor human judgment.']]},
 {title:['Sales diversity','销售多样性'],items:[['Collaborative filtering 可能强化热门产品，降低总体 sales diversity。','Collaborative filtering may reinforce popular products and reduce aggregate sales diversity.'],['课件研究中，purchase-based 的集中效应比 view-based 更强。','In the study presented, purchase-based recommendations concentrate sales more than view-based ones.'],['Lorenz curve 可用于观察销售集中度。','A Lorenz curve can indicate sales concentration.']],takeaway:['Recommendation CTR 应与收入、探索和多样性一起评估。','Evaluate recommendation CTR alongside revenue, discovery and diversity.']},
 {title:['Device 与 journey role','设备与旅程角色'],items:[['Mobile 可支持随时搜索和线下场景；desktop 常承接不同任务。','Mobile supports on-the-go search and offline settings; desktop often serves different tasks.'],['Device、time of day 与使用目的影响 impression、CTR 和 CVR。','Device, time of day and usage purpose affect impressions, CTR and CVR.'],['Mobile CVR 较低，需要检查后续 desktop 或线下 conversion。','A lower mobile CVR calls for examining subsequent desktop or offline conversion.']]},
 {title:['App adoption 与 monetization','App 采用与变现'],items:[['课件中的研究显示，已有 mobile website 时，App adoption 仍可增加购买。','The study presented finds that app adoption can add purchases even when a mobile website already exists.'],['观察 purchase incidence、frequency 与 order value，而不只看下载。','Examine purchase incidence, frequency and order value rather than downloads alone.'],['Hard landing 为 pay-or-churn；soft landing 保留部分免费功能。','Hard landing requires payment or churn; soft landing retains some free functionality.']]},
 {title:['平台扩展与 App failure','Platform expansion & app failure'],items:[['新增 delivery app 可能产生协同；效果取决于时间、门店与竞争环境。','Adding a delivery app may create synergy, depending on timing, stores and competition.'],['App outage 可减少线下购买，因为 App 也支持消费者的研究。','An app outage can reduce offline purchases because the app also supports customer research.'],['分析 channel switching 与 search abandonment，衡量整体损失。','Examine channel switching and search abandonment to assess total losses.']]},
 {title:['Gamification','游戏化与业务价值'],items:[['Game rewards 与接近奖励的 goal-gradient 可以提高 engagement。','Game rewards and proximity to a reward can increase engagement through the goal-gradient effect.'],['Flow 可能让游戏活动与实际价值行动脱节。','Flow can disconnect game activity from value-relevant actions.'],['奖励门槛可以连接游戏参与与有价值的用户任务。','Reward gates can connect game participation to valuable user tasks.']]},
 {title:['Geo-targeting 家族','Location-based targeting'],items:[['Geofencing：某区域内所有人。Geotargeting：区域内符合条件的人。','Geofencing: everyone in an area. Geotargeting: qualifying people in that area.'],['Geoconquesting：竞争对手附近。Beaconing：自有地点的精确互动。','Geoconquesting: near competitors. Beaconing: precise interactions at owned locations.'],['位置可与天气、近期行为和时间组合，并考虑 permission 与责任。','Combine location with weather, recent behavior and time while considering permission and responsibility.']]}
],visual:{title:['移动渠道的跨渠道价值','The cross-channel value of mobile'],steps:[['App 搜索','App search'],['产品了解','Product learning'],['切换渠道','Channel switching'],['线上或线下购买','Online or offline purchase'],['整体绩效','Total performance']],note:['低 App 内 CVR 不足以否定 App 价值；需要观察跨渠道 outcomes。','A low in-app CVR alone does not rule out app value; examine cross-channel outcomes.']}}
);

DMA.tutorials=[
{title:['Tutorial 1：变量、回归与概率归因','Tutorial 1: variables, regression & probabilistic attribution'],source:'t1',concepts:[
 {title:['GA4 与 BigQuery 的分析层级','GA4 & BigQuery analytical granularity'],items:[['Aggregate data 用于总体 traffic、device 和 source 比较。','Aggregate data support comparisons of traffic, devices and sources.'],['Individual / session-level data 支持 journey、sequence 和 micro-conversion 分析。','Individual or session-level data support journey, sequence and micro-conversion analysis.'],['Micro-conversions 包括查看细节、加入购物车、加入 wishlist 等。','Micro-conversions include viewing details, adding to cart and adding to a wishlist.']]},
 {title:['Y 的类型决定起点','Start with the outcome scale'],items:[['Nominal、ordinal、interval、ratio 区分不同测量层级。','Nominal, ordinal, interval and ratio distinguish measurement scales.'],['课程基础规则：连续 Y 用 linear；二元 0/1 Y 用 logistic。','The course’s introductory rule: use linear regression for continuous Y and logistic regression for binary Y.'],['真实建模也要检查分布、假设与数据结构，count data 未必适合 OLS。','Actual modeling also requires checking distributions, assumptions and data structure; count data do not always suit OLS.']]},
 {title:['Dummies 与 reference group','虚拟变量与参照组'],items:[['K 个类别创建 K−1 个 dummies，并明确 reference group。','For K categories, create K−1 dummies and define the reference group.'],['Dummy 系数解释相对于 reference 的差异。','Interpret a dummy coefficient as a difference from the reference group.'],['保留原始分类变量，另建 recoded variables。','Keep the original categorical variable and create separate recoded variables.']]},
 {title:['Linear regression 读表','Interpreting linear regression'],items:[['Unstandardized B 表示控制其他 X 后，X 增加一单位关联的 Y 变化。','Unstandardized B represents the change in Y associated with a one-unit increase in X, holding other predictors constant.'],['Standardized beta 帮助比较同一模型中不同量纲的关联强度。','Standardized beta helps compare associations on different scales within the same model.'],['p-value、方向、大小与业务重要性都要解释。','Interpret p-values, direction, magnitude and business importance.'],['不显著不等于证明没有作用，可能存在样本与模型限制。','Non-significance does not prove no effect; sample and model limitations may matter.']]},
 {title:['Interactions','交互项'],items:[['把 X1 × X2 加入模型，并保留主效应。','Add X1 × X2 to the model while retaining the main effects.'],['Y = a + b1X1 + b2X2 + b3X1X2；X1 的斜率为 b1 + b3X2。','Y = a + b1X1 + b2X2 + b3X1X2; the slope of X1 is b1 + b3X2.'],['存在交互时，主效应是在其他交互变量为 0 / reference 时的效果。','With an interaction, a main effect is conditional on the other interacting variable being zero or at the reference category.']]},
 {title:['Logistic regression 读表','Interpreting logistic regression'],items:[['Binary Y 用 0/1；B 作用于 log-odds，Exp(B) 是 odds ratio。','Code a binary Y as 0/1; B acts on log-odds and Exp(B) is an odds ratio.'],['Odds ratio > 1 表示 odds 增加；< 1 表示下降。','An odds ratio above 1 indicates higher odds; below 1 indicates lower odds.'],['OR = 2 表示 odds 翻倍，不能直接说 probability 翻倍。','OR = 2 means the odds double, not that probability necessarily doubles.']]},
 {title:['Probabilistic attribution','概率归因的路径逻辑'],items:[['Tutorial 按顺序计算新增触点带来的 marginal contribution。','The tutorial calculates marginal contributions as touches are added in sequence.'],['CAB 路径：C 的贡献为 P(C)，A 为 P(CA)−P(C)，B 为 P(CAB)−P(CA)。','For path CAB: credit for C is P(C), A is P(CA)−P(C), and B is P(CAB)−P(CA).'],['这里沿用课件示例的零 baseline；存在 baseline 时要单独处理。','This follows the slide example’s zero baseline; a nonzero baseline needs separate treatment.'],['换成 BAC 或 ABC 后，顺序与边际贡献可能改变。','Changing to BAC or ABC can change the sequence and marginal contributions.']]},
 {title:['软件与学习重点','Software & learning focus'],items:[['SPSS、R 和 Python 都可以实现相同模型逻辑。','SPSS, R and Python can implement the same model logic.'],['课程重点是选模型与读结果，R / Python 附录是可选扩展。','The course emphasizes model choice and interpretation; the R and Python appendices are optional extensions.']]}
],visual:{title:['回归工作流程','Regression workflow'],steps:[['明确 Y','Define Y'],['检查 scale','Check scale'],['准备 X 与 dummy','Prepare X & dummies'],['估计与诊断','Estimate & diagnose'],['解释与行动','Interpret & act']],note:['观察性模型支持关联和预测；更强的因果结论需要额外识别依据。','Observational models support associations and prediction; stronger causal claims require additional identification.']}}
,
{title:['Tutorial 2 / Part 1：网页采集','Tutorial 2 / Part 1: web scraping'],source:'t2a',concepts:[
 {title:['采集对象与分析问题','Collection unit & analytical question'],items:[['Scraping 获取网页可见的 on-site data，不能直接得到隐藏的 clickstream。','Scraping collects visible on-site data, not hidden clickstream behavior.'],['先定义一行代表什么，再定义需要哪些字段。','Define what one row represents before choosing fields.']]},
 {title:['Container 与 sub-elements','容器与子元素'],items:[['Container / parent 定义观察单位，如每个产品、评论或列表项。','The container or parent defines the observation unit, such as a product, review or listing.'],['Child elements 定义列，如 price、rating、text、date。','Child elements define columns, such as price, rating, text and date.']]},
 {title:['Pagination 与关联','翻页与字段关联'],items:[['Pagination 指示 next-page、加载更多或列表持续遍历。','Pagination handles next-page actions, loading more or traversing a list.'],['ParseHub 的 relative select 把子字段连接到正确的 parent。','ParseHub’s relative select connects child fields to the correct parent.'],['核对每一行中的字段确实来自同一观察单位。','Check that all fields in a row belong to the same observation unit.']]},
 {title:['导出与准备','Export & preparation'],items:[['导出 CSV、XLS 或 JSON，再检查行列、分隔符与字段类型。','Export CSV, XLS or JSON, then check rows, columns, delimiters and field types.'],['清理缺失、重复和格式，并保留原始文件。','Prepare missing values, duplicates and formats while retaining the raw file.'],['之后才生成 dummies、features 并运行分析。','Create dummies and features before running analysis.']]},
 {title:['工具选择与可选内容','Tool selection & optional material'],items:[['课程主要演示 ParseHub。Browser extensions 适合较简单任务。','The course primarily demonstrates ParseHub. Browser extensions suit simpler tasks.'],['Python / R 支持复杂任务，但需要更多 coding。附录包含相关入门演示。','Python and R support complex tasks but require more coding; the appendices provide introductory demonstrations.'],['课件里的平台接口和采集许可具有版本语境，实际采集需检查当前条件。','Platform interfaces and permissions in the slides are version-specific; actual collection requires checking current conditions.']]}
],visual:{title:['Scraping 的三步结构','The three-part scraping structure'],steps:[['Container：一行','Container: a row'],['Children：各列','Children: columns'],['Pagination：遍历','Pagination: traversal']],note:['先建立稳定的数据结构，再考虑采集规模。','Establish a stable data structure before scaling collection.']}}
,
{title:['Tutorial 2 / Part 2：Sentiment 与 topic','Tutorial 2 / Part 2: sentiment & topics'],source:'t2b',concepts:[
 {title:['Lexicon 与 contextual methods','词典与语境方法'],items:[['Lexicon 快速匹配词语，成本较低，但容易遗漏否定、比较和 sarcasm。','Lexicons match words quickly at lower cost, but may miss negation, comparisons and sarcasm.'],['Contextual / semantic methods 利用句子含义，但仍需要验证。','Contextual or semantic methods use sentence meaning but still need validation.']]},
 {title:['Evaluative Lexicon','评价词典工具'],items:[['输入文本列，输出 valence、extremity 和 emotionality 等量化特征。','Provide a text column to obtain measures such as valence, extremity and emotionality.'],['解释每个变量的定义，再与其他 outcome 合并。','Interpret each variable definition before combining it with outcomes.'],['CSV 分隔符与编码必须正确，不应为导入而随意破坏原文。','CSV delimiters and encoding must be correct; avoid arbitrarily damaging source text to import it.']]},
 {title:['TextBlob','基础情感评分'],items:[['Polarity 通常在 −1 到 +1，subjectivity 在 0 到 1。','Polarity typically ranges from −1 to +1; subjectivity ranges from 0 to 1.'],['逐条文本生成 scores，再保留记录 ID 与原文。','Generate scores per text while retaining the record ID and original text.'],['需要关注语言、领域、语境和抽样验证。','Check language, domain, context and sample-based validation.']]},
 {title:['Topic modeling 与 classification','主题发现与主题分类'],items:[['LDA / STM 用于发现潜在主题，结果需要人工命名和解释。','LDA and STM discover latent topics that require human labeling and interpretation.'],['Hugging Face zero-shot 可按给定 labels 对 topic / emotion 分类。','Hugging Face zero-shot methods classify topics or emotions using supplied labels.'],['预定义标签的 classification 与探索性 topic modeling 应区分。','Distinguish predefined-label classification from exploratory topic modeling.']]},
 {title:['Topic × sentiment','主题与情感交叉'],items:[['按主题查看情绪方向与数量，比总体平均分更可行动。','Topic-level sentiment direction and volume are more actionable than an overall average.'],['负面主题可定位 product、service 或 journey 痛点。','Negative topics can identify product, service or journey pain points.'],['再用 correlation / regression 检查与 rating、engagement 等结果的关系。','Use correlation or regression to examine relationships with ratings, engagement or other outcomes.']]},
 {title:['质量检查','Quality checks'],items:[['随机抽样阅读原文，检查 neutral、否定、讽刺和多主题句。','Read a random sample of original texts and inspect neutral labels, negation, sarcasm and multiple topics.'],['Score 是模型对文字的估计，不是消费者真实态度的直接测量。','A score is a model’s estimate from language, not a direct measure of the consumer’s true attitude.']]}
],visual:{title:['文本分析流程','Text analytics workflow'],steps:[['保留原文与 ID','Retain text & IDs'],['提取 scores / topics','Extract scores & topics'],['人工抽查','Human spot-check'],['合并 outcome','Join outcomes'],['解释业务含义','Interpret implications']],note:['Topic 告诉你 WHAT，sentiment 告诉你 HOW；两者共同帮助确定改善方向。','Topics indicate WHAT is discussed; sentiment indicates HOW it is evaluated. Together they help guide improvements.']}}
];

DMA.sources=[
 {id:'w1',title:['Week 1：基础、平台、数据、指标与归因','Week 1: foundations, platforms, data, metrics & attribution'],file:'DMA_2526_Lecture_Week1_31102025_EPMS.pdf',pages:['60 页；主要学习内容第 7–60 页。','60 pages; main learning content on pages 7–60.']},
 {id:'t1',title:['Tutorial 1：变量、回归与概率归因','Tutorial 1: variables, regression & probabilistic attribution'],file:'DMA_2526_Tutorial_Week1_3031102025_FTBA.pdf',pages:['50 页；GA 第 2–9 页，回归第 10–35 页，概率归因第 42–45 页，软件附录为可选扩展。','50 pages; GA on pages 2–9, regression on 10–35, probabilistic attribution on 42–45; software appendices are optional.']},
 {id:'w2',title:['Week 2：归因挑战、全渠道、社交媒体与非结构化数据','Week 2: attribution challenges, omnichannel, social & unstructured data'],file:'DMA_2526_Lecture_Week2_07112025_EPMS.pdf',pages:['62 页；归因第 2–13 页，全渠道第 14–21 页，社交媒体第 22–43 页，非结构化数据第 44–61 页。','62 pages; attribution on 2–13, omnichannel on 14–21, social on 22–43, unstructured data on 44–61.']},
 {id:'t2a',title:['Tutorial 2 / Part 1：Scraping','Tutorial 2 / Part 1: scraping'],file:'DMA_2526_Tutorial_Week2_Part1_07112025_EPMS.pdf',pages:['48 页；主要采集逻辑与 ParseHub 第 2–22 页，其后 Python / R / DataMiner 为扩展。','48 pages; collection logic and ParseHub on 2–22, followed by Python, R and DataMiner extensions.']},
 {id:'t2b',title:['Tutorial 2 / Part 2：NLP、Sentiment 与 topic','Tutorial 2 / Part 2: NLP, sentiment & topics'],file:'DMA_2526_Tutorial_Week2_Part2_07112025_EPMS.pdf',pages:['47 页；概念第 2–16 页，Evaluative Lexicon 第 17–21 页，TextBlob 与 zero-shot 第 22–41 页。','47 pages; concepts on 2–16, Evaluative Lexicon on 17–21, TextBlob and zero-shot on 22–41.']},
 {id:'w3',title:['Week 3：社交文本、Paralanguage 与 AI','Week 3: social text, paralanguage & AI'],file:'DMA_2526_Lecture_Week3_14112025_EPMS.pdf',pages:['主要内容：sentiment / topic、语言与互动、emoji、PARA、多模态及 GenAI。','Main content: sentiment and topics, language and engagement, emojis, PARA, multimodality and GenAI.']},
 {id:'genai',title:['GenAI 补充课件','GenAI add-on slides'],file:'DMA_2526_Lecture_Week3_14112025_EPMS_AddOn_Slides_GENAI.pdf',pages:['主要内容：GenAI 应用、prompt 结构、AI agents 及可靠性。','Main content: GenAI applications, prompt structure, AI agents and reliability.']},
 {id:'w4',title:['Week 4：评论、评分、SEO 与 SEA','Week 4: reviews, ratings, SEO & SEA'],file:'DMA_2526_Lecture_Week4_21112025_EPMS.pdf',pages:['52 页；评论第 2–21 页，search 第 22–51 页。','52 pages; reviews on 2–21, search on 22–51.']},
 {id:'w5',title:['Week 5：定价与个性化定向','Week 5: pricing & personalized targeting'],file:'DMA_2526_Lecture_Week5_28112025_EPMS.pdf',pages:['25 页；定价第 2–12 页，个性化、A/B 与情绪第 13–24 页。','25 pages; pricing on 2–12, personalization, A/B testing and emotion on 13–24.']},
 {id:'w6',title:['Week 6：推荐、移动、Apps 与地理营销','Week 6: recommenders, mobile, apps & geomarketing'],file:'DMA_2526_Lecture_Week6_05122025_EPMS.pdf',pages:['45 页；推荐第 2–16 页，移动第 17–26 页，Apps 第 27–36 页，位置营销第 37–42 页。','45 pages; recommenders on 2–16, mobile on 17–26, apps on 27–36, location marketing on 37–42.']},
 {id:'guest',title:['Guest lecture：生成式 AI（补充）','Guest lecture: generative AI (supplementary)'],file:'2025-11 DMA Guest Lecture Bart Santing.pdf',pages:['44 页；包括 human–AI collaboration、训练、bias、prompting、RAG 与 agents。','44 pages; includes human–AI collaboration, training, bias, prompting, RAG and agents.']},
 {id:'recap',title:['Recap：课程重点与应用推理','Recap: course priorities & applied reasoning'],file:'DMA_2526_Lecture_Week6_Tips_Exam_Recap_AdditionalSlides_EPMS.pdf',pages:['23 页；六周主题第 13–18 页，答题推理第 20–22 页。','23 pages; six-week topics on 13–18, answer reasoning on 20–22.']}
];

DMA.review=[
 {q:['CTR 很高，但购买很少，应如何解释？','CTR is high, but purchases are low. How should this be interpreted?'],a:['CTR 反映点击反应。继续检查 CVR、landing-page friction、信息一致性与流量意图。选择一个机制提出实验，并用最终 conversion / cost 指标判断。','CTR captures click response. Check CVR, landing-page friction, message consistency and traffic intent. Test one proposed mechanism and evaluate the final conversion and cost outcomes.']},
 {q:['Last-click 为什么可能低估 social media？','Why might last-click undervalue social media?'],a:['Social 可能负责 introduction 或 assist，而另一个渠道完成购买。Last-click 把 credit 给收尾渠道。比较归因规则并考虑实验或 MMM，不能直接把差异当成某模型出错。','Social may provide introduction or assistance while another channel closes the purchase. Last-click credits the closer. Compare rules and consider experiments or MMM rather than treating disagreement alone as a model error.']},
 {q:['Y 是购买 / 未购买，应该选什么回归？','Which regression fits a purchase / no-purchase outcome?'],a:['使用 logistic regression，因为 Y 是二元变量。解释 coefficient direction、significance 和 Exp(B)；Exp(B) 是 odds ratio，不能直接当作 probability ratio。','Use logistic regression because Y is binary. Interpret coefficient direction, significance and Exp(B). Exp(B) is an odds ratio, not a probability ratio.']},
 {q:['4.2 分为何在不同平台含义不同？','Why can a 4.2 rating mean different things on different platforms?'],a:['平台评分分布、用户构成和评价机制不同。先看 percentile、distribution 与文字 review，再比较表现。','Rating distributions, users and evaluation mechanisms differ. Examine percentiles, distributions and review text before comparing performance.']},
 {q:['为什么同时使用 topic 和 sentiment？','Why combine topics with sentiment?'],a:['总体 sentiment 看不出问题具体发生在哪里。Topic × sentiment 可以识别消费者对价格、服务等主题的不同评价，从而提出具体行动。','Overall sentiment does not locate the issue. Topic × sentiment distinguishes reactions to price, service or other themes and supports specific actions.']},
 {q:['SEO 与 SEA 如何分配？','How should SEO and SEA be allocated?'],a:['结合目标时限与 search intent。SEA 可支持即时战术需求，SEO 面向较长期的相关性建设。比较最终转化和价值，同时关注两者协同。','Consider time horizon and search intent. SEA supports immediate tactical needs, while SEO builds longer-term relevance. Compare eventual conversion and value and consider their synergy.']},
 {q:['Mobile CVR 低，是否应该停止投入？','Should low mobile CVR lead to stopping mobile investment?'],a:['先检查 mobile 是否支持搜索和 offline / desktop conversion。跨设备、跨渠道及时间窗口可能遗漏贡献。低单渠道 CVR 不足以推导整体低价值。','Check whether mobile supports search and later offline or desktop conversion. Cross-device, cross-channel and window limitations can miss contributions. Low single-channel CVR alone does not imply low total value.']},
 {q:['推荐 CTR 上升是否代表全面改善？','Does rising recommendation CTR establish overall improvement?'],a:['还要检查 sales、order value、sales diversity 和产品探索。Collaborative filtering 可能强化热门商品，造成销售集中。','Also examine sales, order value, sales diversity and product discovery. Collaborative filtering can reinforce popular items and concentrate sales.']},
 {q:['何时能够使用 causal language？','When is causal language justified?'],a:['随机 A/B / holdout 或可信的因果识别设计能提供更强支持。普通观察性 regression 的显著系数通常只表明条件关联。','Randomized A/B tests, holdouts or credible identification designs provide stronger support. A significant coefficient in ordinary observational regression generally shows a conditional association.']},
 {q:['为什么 retargeting 不一定越早越好？','Why is earlier retargeting not always better?'],a:['弃购可能来自不合适的时机或需求。过早提醒可能引起反感。课件研究说明 timing 是条件，需要通过随机实验验证具体策略。','Cart abandonment may reflect timing or need. An early reminder can backfire. The study in the slides makes timing a boundary condition that should be tested with a randomized design.']}
];

DMA.guest={title:['Guest lecture：GenAI 的可靠应用','Guest lecture: using GenAI reliably'],concepts:[
 {title:['训练与偏差','Training & bias'],items:[['Pre-training 学习语言规律；supervised fine-tuning 使用示范；RLHF 使用人类反馈。','Pre-training learns language regularities; supervised fine-tuning uses demonstrations; RLHF uses human feedback.'],['Training-data bias 与 human–AI interaction bias 都可能影响输出。','Both training-data bias and bias in human–AI interaction can affect outputs.'],['避免 automation bias，也不要忽略可用价值而产生 algorithm aversion。','Avoid automation bias without dismissing useful capabilities through algorithm aversion.']]},
 {title:['Grounding 与 human collaboration','信息依据与人机协作'],items:[['RAG 将相关材料带入上下文；API 可以提供具体业务数据。','RAG brings relevant documents into context; APIs can supply specific business data.'],['加入角色、任务、上下文、限制、格式和质量标准。','Specify role, task, context, constraints, format and quality standards.'],['AI 与 human communication 可互补；agents 需要治理，并非每个 workflow 都需要 agent。','AI and human communication can complement each other; agents need governance and are not required for every workflow.']]}
]};

// References use PDF page numbers (including cover pages), not printed slide labels.
const DMA_PAGE_REFS={
 week1:[[10,11],[12,16],[17,29],[30,40],[46,52],[53,58]],
 week2:[[3,3],[4,7],[5,6],[8,12],[14,21],[28,31],[32,43],[44,61]],
 week3:[[4,9],[10,11],[12,12],[15,24],[17,21],[25,27],[28,34]],
 week4:[[3,10],[12,13],[14,17],[18,21],[23,28],[31,37],[38,47],[48,51]],
 week5:[[3,9],[10,12],[14,18],[20,22],[16,17],[19,19],[23,24]],
 week6:[[6,8],[9,12],[13,15],[14,14],[17,26],[28,30],[31,34],[35,36],[37,42]],
 t1:[[2,9],[10,16],[20,22],[24,27],[28,29],[30,35],[42,45],[36,41]],
 t2a:[[3,5],[10,13],[14,20],[21,22],[6,8]],
 t2b:[[3,10],[17,21],[22,36],[11,13],[14,15],[9,10]]
};
DMA.weeks.forEach(w=>w.concepts.forEach((c,i)=>{c.refs=[{id:w.source,pages:DMA_PAGE_REFS[w.id][i]}]}));
DMA.weeks.find(w=>w.id==='week3').concepts.at(-1).refs.push({id:'genai',pages:[3,12]});
DMA.tutorials.forEach(t=>t.concepts.forEach((c,i)=>{c.refs=[{id:t.source,pages:DMA_PAGE_REFS[t.source][i]}]}));
DMA.guest.concepts[0].refs=[{id:'guest',pages:[16,30]}];
DMA.guest.concepts[1].refs=[{id:'guest',pages:[34,41]}];
DMA.sources.forEach(s=>{s.url=`materials/${s.id}.pdf`});
DMA.review.forEach((q,i)=>{q.refs=[[
 {id:'w1',pages:[37,42]},{id:'w2',pages:[3,12]},{id:'t1',pages:[30,35]},
 {id:'w4',pages:[6,10]},{id:'w3',pages:[10,11]},{id:'w4',pages:[48,51]},
 {id:'w6',pages:[21,26]},{id:'w6',pages:[14,14]},{id:'w5',pages:[16,17]},
 {id:'w5',pages:[19,19]}
][i]]});
