window.DMAFrameworkUI={create({bi,esc,chainSources,getLang}){
const types={concept:['概念框架／视角','Conceptual framework / lens'],decision:['决策结构','Decision structure'],model:['方法／模型','Method / model']};
const visuals=DMAFrameworkVisuals.create({bi,esc,getLang});
const find=id=>DMA.frameworks.find(f=>f.id===id);
const units={'1':['Week 1','Week 1'],'2':['Week 2','Week 2'],'3':['Week 3','Week 3'],'4':['Week 4','Week 4'],'5':['Week 5','Week 5'],'6':['Week 6','Week 6'],T:['Tutorial','Tutorial'],AI:['AI 补充','AI supplement']};
let favorites=new Set(),query='',type='',week='',favoriteOnly=false,quickQuery='',context='',quickId='';
try{const saved=JSON.parse(localStorage.getItem('dma-framework-favorites')||'[]');if(Array.isArray(saved))favorites=new Set(saved.filter(id=>find(id)))}catch{}
const text=p=>getLang()==='en'?p[1]:p[0];
const searchText=f=>[f.title,f.purpose,f.when,...f.parts].flat().join(' ')+' '+f.keys;
const matches=(f,q)=>q.trim().toLowerCase().split(/\s+/).every(term=>searchText(f).toLowerCase().includes(term));
const star=f=>`<button type="button" class="fw-star" data-fw-star="${f.id}" aria-pressed="${favorites.has(f.id)}" aria-label="${esc(text(favorites.has(f.id)?['取消收藏：','Remove favorite: ']:['收藏：','Favorite: '])+text(f.title))}">${favorites.has(f.id)?'★':'☆'}</button>`;
const summary=(p,body)=>`<details class="fw-fold"><summary>${bi(p,'span','bi')}</summary><div>${body}</div></details>`;
function card(f){return `<article class="fw-card" data-fw-card="${f.id}"><div class="fw-card-top"><span>${bi(types[f.type],'span','bi')}</span>${star(f)}</div><a class="fw-card-main" href="#frameworks/${f.id}">${bi(f.title,'h2','bi')}${visuals.badge(f)}${visuals.diagram(f,true)}${bi(f.purpose,'p','bi')}<span class="fw-card-bottom">${bi(units[f.week],'span','bi')}${bi(['打开图解 →','Explore diagram →'],'span','bi')}</span></a></article>`}
function directory(){
 const filters=`<div class="fw-filters"><label><span class="sr-only">类型 / Type</span><select id="fw-type" data-fw-select="type"><option value="">${esc(text(['全部类型','All types']))}</option>${Object.entries(types).map(([id,p])=>`<option value="${id}"${type===id?' selected':''}>${esc(text(p))}</option>`).join('')}</select></label><label><span class="sr-only">课程 / Course</span><select id="fw-week" data-fw-select="week"><option value="">${esc(text(['全部课程','All units']))}</option>${Object.entries(units).map(([id,p])=>`<option value="${id}"${week===id?' selected':''}>${esc(text(p))}</option>`).join('')}</select></label><button type="button" data-fw-favorites aria-pressed="${favoriteOnly}">${bi(['★ 我的常用','★ My favorites'],'span','bi')}</button><button type="button" class="fw-reset" data-fw-reset>${bi(['清除筛选','Clear filters'],'span','bi')}</button></div>`;
 const boundaries=bi(['收录 16 个课程条目，不表示课程只有 16 个框架，也不表示所有条目都已完成全面逻辑审计。概念视角、决策结构和方法分开标注。','Sixteen course entries: not an exhaustive framework count or a claim of completed logical audits. Lenses, decision structures and methods are distinguished.'],'p','bi')+bi(DMA.frameworkReview.scope,'p','bi')+bi(DMA.frameworkReview.automatedChecks,'p','bi')+bi(['应用检查、操作、模板和标明的示例是教学补充，不是老师逐字原文；个人笔记与指定阅读全文仍待核实。收藏仅保存在当前浏览器，网页不会自动分析或评价你的答案。','Application checks, operations, templates and labeled examples are editorial, not verbatim teacher text. Personal notes/full readings remain unverified. Favorites are local; the site does not automatically analyze or grade answers.'],'p','bi');
 return `<section class="fw-library"><header>${bi(['Framework 图解库','Framework visual library'],'h1','page-title')}${bi(['先理解结构，再核对证据条件，最后才调用模板。','Understand the structure, check evidence conditions, then apply a template.'],'p','lead')}</header><aside class="fw-review-update" data-fw-review-date="${DMA.frameworkReview.date}">${bi(['本次逻辑修补 · 2026-10-03','Logic repair · 2026-10-03'],'strong','bi')}${bi(['MMM 补齐实际 Y；推荐补齐三类候选；AI 标明摘要与机制缺口。16 个条目新增应用检查，均为教学补充。','Observed Y restored in MMM; three recommendation candidates; AI abstract/mechanism gaps marked. Editorial application checks added to all 16 entries.'],'p','bi')}<div>${['mmm','recommender','automation-augmentation'].map(id=>`<a href="#frameworks/${id}">${bi(find(id).title,'span','bi')}</a>`).join('')}</div></aside><div class="fw-search-box"><label for="fw-search">${bi(['你想解决什么问题？','What are you trying to solve?'],'span','bi')}</label><input id="fw-search" data-fw-search="page" type="search" value="${esc(query)}" placeholder="${esc(text(['搜索：预算、品牌、情绪、归因、A/B…','Search: budget, brand, emotions, attribution, A/B…']))}"></div>${filters}<p class="fw-results" id="fw-count" role="status"></p><div class="fw-grid">${DMA.frameworks.map(card).join('')}</div><div id="fw-empty" class="fw-empty" hidden>${bi(['没有匹配项。试试换个关键词，或清除筛选。','No matches. Try another keyword or clear filters.'],'p','bi')}</div>${summary(['来源、分类与审查范围','Provenance, classification and review scope'],boundaries)}</section>`
}
function applicationGate(f){return `<section class="fw-gate" data-fw-gate="${f.id}">${bi(['应用前：先检查证据','Before applying: check the evidence'],'h2','bi')}${bi(['教学补充 · 不是老师原有判定规则，不会自动判断材料是否足够。','Editorial checks, not original teacher rules or automatic evidence certification.'],'p','fw-gate-origin bi')}<details><summary>${bi(['需要什么 → 能判断什么 → 何时暂停 → 什么会推翻建议','Evidence → supported judgment → pause → counterevidence'],'span','bi')}</summary><dl>${[['need',['最低材料','Minimum evidence']],['proceed',['可以推进到哪','Supported next step']],['stop',['必须暂停什么','Pause this claim']],['challenge',['关键反证','Counterevidence']]].map(([key,p])=>`<div class="fw-gate-${key}">${bi(p,'dt','bi')}${bi(f.gate[key],'dd','bi')}</div>`).join('')}</dl></details></section>`}
function learningNotes(f){if(!f.notes?.length)return '';const labels={source:['课件转述','Slide paraphrase'],'source-analysis':['课件＋标明的教学分析','Slides + labeled editorial analysis'],example:['教学假设例子','Hypothetical teaching example'],gap:['待核实／不可推出','Unverified / unsupported']};return `<details class="fw-fold fw-learning-notes"><summary>${bi(f.id==='automation-augmentation'?['解释与材料缺口','Explanation and evidence gaps']:f.id==='recommender'?['具体实现：元路径，不代表全部混合方法','Specific implementation: meta-paths, not all hybrids']:['实际 Y 与拟合值有什么区别？','How do observed Y and fitted values differ?'],'span','bi')}</summary><div>${f.notes.map(n=>`<section data-fw-note-basis="${n.basis}">${bi(labels[n.basis],'span','fw-note-basis bi')}${bi(n.title,'h3','bi')}${bi(n.body,'p','bi')}${n.flow.length?`<ol class="fw-note-flow" aria-label="教学流程 / Teaching flow">${n.flow.map(p=>bi(p,'li','bi')).join('')}</ol>`:''}${n.refs.length?chainSources(n.refs):''}</section>`).join('')}</div></details>`}
function template(f){const lang=getLang();const pick=p=>lang==='both'?p.join(' / '):p[lang==='en'?1:0];return pick(['调用：','Apply: '])+pick(f.title)+'\n\n'+pick(['我的问题：［待填写］','My question: [fill in]'])+'\n'+pick(['可用材料及缺口：［待填写］','Available evidence and gaps: [fill in]'])+'\n\n'+pick(['应用检查（教学补充）：','Application checks (editorial):'])+'\n'+[['need',['最低材料：','Minimum evidence: ']],['proceed',['可以推进到哪：','Supported next step: ']],['stop',['暂停条件：','Pause condition: ']],['challenge',['关键反证：','Counterevidence: ']]].map(([k,p])=>pick(p)+pick(f.gate[k])).join('\n')+'\n'+pick(['我的证据是否支持继续、为什么：［待填写；不支持就暂停］','Does my evidence support proceeding, and why: [fill in; otherwise pause]'])+'\n\n'+f.fields.map((p,i)=>(i+1)+'. '+pick(p)+': '+pick(['［待填写］','[fill in]'])).join('\n')+'\n\n'+pick(['证据满足时才可争取的输出：','Output to pursue only with adequate evidence: '])+pick(f.output)+'\n'+pick(['要求：区分事实、假设和推断；标注来源；缺少证据写“待核实”，不生成确定结论。','Requirements: separate facts, assumptions and inferences; cite sources; mark missing evidence unverified rather than generate a definite conclusion.'])}
function detail(f,quick=false){
 const evidenceNote=['图上已分别标注：课件结构重绘、课件概念整理、假设示例、应用空白模板。重绘并非原图截图；概念整理的布局为教学设计。操作建议与模板不是老师逐字原文，假设示例不是实测结果。','Each visual is labeled: slide-structure redraw, slide-concept map, hypothetical example, or blank application template. Redraws are not screenshots; concept-map layouts are editorial. Operations/templates are not verbatim teacher text; hypothetical examples are not observed results.'];
 const head=`<div class="fw-detail-back">${quick?`<button type="button" data-fw-quick-back>${bi(['← 返回速查','← Back to lookup'],'span','bi')}</button>`:`<a href="#frameworks">${bi(['← 全部框架','← All frameworks'],'span','bi')}</a>`}${star(f)}</div><p class="fw-meta">${bi(types[f.type],'span','bi')}<span aria-hidden="true">·</span>${bi(units[f.week],'span','bi')}</p>${bi(f.title,'h1','page-title')}${bi(f.purpose,'p','fw-purpose bi')}${f.gap?bi(f.gap,'p','fw-gap-status bi'):''}`;
 const folds=summary(['何时用、怎样调用','When and how to apply'],`<div class="fw-when">${bi(['什么时候调用','When to use'],'strong','bi')}${bi(f.when,'p','bi')}</div><ol class="fw-apply">${f.apply.map(p=>bi(p,'li','bi')).join('')}</ol>`)+summary(['概念对照 · 课件转述','Concept reference · slide paraphrase'],`<ul class="fw-concept-list">${f.parts.map(p=>bi(p,'li','bi')).join('')}</ul>`)+summary(['看一个例子','See an example'],bi(f.example,'p','bi'))+summary(['不能从它推出什么？','What does it not establish?'],bi(f.limit,'p','bi'))+summary(['原课件与页码依据','Original slides and page references'],chainSources(f.refs)+bi(evidenceNote,'p','bi small-meta'));
 const callTemplate=`<details class="fw-template"><summary>${bi(['调用模板 · 展开后复制／填写','Application template · expand to copy or fill'],'span','bi')}</summary><label>${bi(['填写后请复制留存；离开此卡片不会自动保存模板草稿。','Copy completed text before leaving; template drafts are not automatically saved.'],'span','bi')}<textarea rows="12" data-fw-template="${f.id}">${esc(template(f))}</textarea></label><button type="button" data-fw-copy>${bi(['复制模板','Copy template'],'span','bi')}</button><p class="fw-copy-status" role="status"></p></details>`;
 return `<article class="fw-detail" data-fw-detail="${f.id}">${head}${visuals.diagram(f)}${learningNotes(f)}${applicationGate(f)}${folds}${callTemplate}<div class="fw-linked-chains">${bi(['继续理解推理','Continue the reasoning'],'h2','fw-section bi')}${f.chains.map(id=>{const c=DMA.chains.find(x=>x.id===id);return `<a href="#chains/${id}"${quick?' data-fw-learn':''}>${bi(c.title,'span','bi')} →</a>`}).join('')}</div></article>`
}
function syncStars(){document.querySelectorAll('[data-fw-star]').forEach(el=>{const f=find(el.dataset.fwStar),saved=favorites.has(f.id);el.textContent=saved?'★':'☆';el.setAttribute('aria-pressed',saved);el.setAttribute('aria-label',text(saved?['取消收藏：','Remove favorite: ']:['收藏：','Favorite: '])+text(f.title))})}
function filterPage(){let count=0;document.querySelectorAll('[data-fw-card]').forEach(el=>{const f=find(el.dataset.fwCard),visible=matches(f,query)&&(!type||f.type===type)&&(!week||f.week===week)&&(!favoriteOnly||favorites.has(f.id));el.hidden=!visible;if(visible)count++});const result=document.querySelector('#fw-count');if(result)result.innerHTML=bi([`${count} / 16 个条目`,`${count} / 16 entries`],'span','bi');const empty=document.querySelector('#fw-empty');if(empty)empty.hidden=count>0}
function quickList(){const sorted=[...DMA.frameworks].sort((a,b)=>(Number(b.chains.includes(context))*2+Number(favorites.has(b.id)))-(Number(a.chains.includes(context))*2+Number(favorites.has(a.id))));return `<label class="fw-quick-search">${bi(['搜索或选一个框架','Search or choose a framework'],'span','bi')}<input type="search" data-fw-search="quick" value="${esc(quickQuery)}" placeholder="${esc(text(['预算 / 品牌 / 情绪 / A/B…','Budget / brand / emotions / A/B…']))}"></label>${bi(['相关条目与收藏优先。点开后仍留在当前页。','Related entries and favorites first. Open without leaving this page.'],'p','bi small-meta')}<div class="fw-quick-list">${sorted.map(f=>`<div data-fw-quick-item="${f.id}"${matches(f,quickQuery)?'':' hidden'}><button type="button" data-fw-quick-id="${f.id}"><span class="fw-thumb">${visuals.diagram(f,true)}</span><span class="fw-quick-text">${bi(f.title,'strong','bi')}${bi(f.purpose,'span','bi')}${f.chains.includes(context)?bi(['与当前知识链相关','Related to this chain'],'span','fw-related bi'):''}</span></button>${star(f)}</div>`).join('')}</div><p id="fw-quick-empty" hidden>${bi(['没有匹配项，请换个关键词。','No matches; try another keyword.'],'span','bi')}</p>`}
function renderQuick(){const body=document.querySelector('#framework-quick-body');body.innerHTML=quickId?detail(find(quickId),true):quickList();initTemplates();syncStars();filterQuick();body.scrollTop=0}
function initTemplates(){document.querySelectorAll('[data-fw-template]').forEach(el=>{if(!el.dataset.defaultText)el.dataset.defaultText=el.value})}
function filterQuick(){if(quickId)return;let n=0;document.querySelectorAll('[data-fw-quick-item]').forEach(el=>{el.hidden=!matches(find(el.dataset.fwQuickItem),quickQuery);if(!el.hidden)n++});const empty=document.querySelector('#fw-quick-empty');if(empty)empty.hidden=n>0}
function syncLang(){document.querySelectorAll('[data-fw-template]').forEach(el=>{const next=template(find(el.dataset.fwTemplate));if(el.value===el.dataset.defaultText){el.value=next;el.dataset.defaultText=next}});const search=document.querySelector('#fw-search');if(search)search.placeholder=text(['搜索：预算、品牌、情绪、归因、A/B…','Search: budget, brand, emotions, attribution, A/B…']);for(const [id,all,dict]of [['fw-type',['全部类型','All types'],types],['fw-week',['全部课程','All units'],units]]){const select=document.getElementById(id);if(select)Array.from(select.options).forEach(o=>o.textContent=text(o.value?dict[o.value]:all))}syncStars();filterPage()}
function openQuick(chain=''){context=chain||((location.hash.startsWith('#chains/'))?location.hash.slice(8):'');quickId='';renderQuick();const modal=document.querySelector('#framework-quick');if(!modal.open)modal.showModal();document.body.classList.add('fw-is-open');document.querySelector('[data-fw-search="quick"]')?.focus()}
function closeQuick(){document.querySelector('#framework-quick').close()}
function bindQuick(){document.querySelector('#framework-quick').addEventListener('close',()=>document.body.classList.remove('fw-is-open'));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.querySelector('#framework-quick').open&&!document.querySelector('#pdf-viewer').open){e.preventDefault();closeQuick()}})}
document.addEventListener('click',e=>visuals.click(e));
return {directory,detail,id:find,init(){initTemplates();filterPage();syncStars()},syncLang,openQuick,click(e){const open=e.target.closest('[data-fw-open]'),favorite=e.target.closest('[data-fw-star]'),select=e.target.closest('[data-fw-quick-id]');if(open)openQuick(open.dataset.fwContext);if(e.target.closest('#framework-quick-close'))closeQuick();if(select){quickId=select.dataset.fwQuickId;renderQuick()}if(e.target.closest('[data-fw-quick-back]')){quickId='';renderQuick()}if(e.target.closest('[data-fw-learn]'))closeQuick();if(favorite){const id=favorite.dataset.fwStar;favorites.has(id)?favorites.delete(id):favorites.add(id);let saved=true;try{localStorage.setItem('dma-framework-favorites',JSON.stringify([...favorites]))}catch{saved=false}syncStars();filterPage();const status=document.querySelector('#fw-global-status');if(status)status.innerHTML=bi(saved?['常用框架已更新，仅保存在当前浏览器。','Favorites updated in this browser only.']:['仅本次会话记住；浏览器无法持久保存。','Remembered this session only; browser storage unavailable.'],'span','bi')}if(e.target.closest('[data-fw-favorites]')){favoriteOnly=!favoriteOnly;e.target.closest('[data-fw-favorites]').setAttribute('aria-pressed',favoriteOnly);filterPage()}if(e.target.closest('[data-fw-reset]')){query='';type='';week='';favoriteOnly=false;document.querySelector('#fw-search').value='';document.querySelector('#fw-type').value='';document.querySelector('#fw-week').value='';document.querySelector('[data-fw-favorites]').setAttribute('aria-pressed','false');filterPage()}const copy=e.target.closest('[data-fw-copy]');if(copy){const box=copy.closest('.fw-template'),input=box.querySelector('textarea'),status=box.querySelector('.fw-copy-status');(async()=>{try{await navigator.clipboard.writeText(input.value);status.innerHTML=bi(['已复制。请补充自己的问题与证据；没有自动执行分析。','Copied. Add your question/evidence; no analysis was automatically performed.'],'span','bi')}catch{input.focus();input.select();status.innerHTML=bi(['无法自动复制，已选中文本，请手动复制。','Automatic copy unavailable; text selected for manual copying.'],'span','bi')}})()}},input(e){if(e.target.dataset.fwSearch==='page'){query=e.target.value;filterPage()}if(e.target.dataset.fwSearch==='quick'){quickQuery=e.target.value;filterQuick()}},change(e){if(e.target.dataset.fwSelect==='type')type=e.target.value;if(e.target.dataset.fwSelect==='week')week=e.target.value;filterPage()},bind:bindQuick};
}};
