/* Course-grounded concepts; application steps/templates are editorial aids. */
(()=>{
const P=(zh,en)=>[zh,en],R=(id,a,b=a)=>({id,pages:[a,b]});
const F=(id,type,week,title,purpose,when,parts,apply,limit,example,fields,output,refs,chains,keys)=>({id,type,week,title,purpose,when,parts,apply,limit,example,fields,output,refs,chains,keys});
DMA.frameworks=[
F('race','concept','1',P('RACE · 营销规划与阶段','RACE · planning and stages'),P('先明确计划和目标，再定位阶段与指标。','Define plan and goals before choosing stages and metrics.'),P('不知道该看曝光、点击、购买还是复购时。','When choosing among exposure, clicks, purchases and repeat buying.'),[
 P('Reach · 触达：让合适的人知道品牌。','Reach: help the right people discover the brand.'),P('Act · 互动与考虑：了解、比较、探索。','Act: exploration, comparison and consideration.'),P('Convert · 转化：完成定义清楚的目标行动。','Convert: complete a clearly defined target action.'),P('Engage · 留存：维持关系、复购与推荐。','Engage: relationships, repeat purchases and advocacy.'),P('Plan · 规划：明确目标、受众和策略；评价后回看计划。','Plan: define goals, audience and strategy; revisit the plan after evaluation.')],
 [P('先制定计划：明确业务目标、受众和策略，再选当前重点阶段。','Plan the objective, audience and strategy before choosing a priority stage.'),P('区分最终结果与过程信号，写清分母和时间窗口。','Separate final outcomes from process signals; define denominators and windows.'),P('检查下一阶段结果并回看计划，避免局部优化损害总目标。','Inspect downstream results and revisit the plan to avoid harmful local optimization.')],
 P('旅程可能往返、跳跃；RACE 不是所有人必经的线性流程，也不证明因果。','Journeys may loop or skip stages; RACE is not a mandatory linear path or causal proof.'),
 P('培训广告点击多但报名少：先定位 Act→Convert 的衔接，再检查页面和报名流程。','Many course-ad clicks but few enrollments: inspect the Act→Convert handoff, page and signup flow.'),
 [P('业务目标','Business objective'),P('当前 RACE 阶段','Current RACE stage'),P('最终结果及定义','Final outcome and definition'),P('过程指标、分母、窗口','Process metrics, denominators, window'),P('下一阶段表现','Downstream performance'),P('候选改动与验证方式','Candidate change and validation')],P('一份目标—阶段—指标—行动对应表。','An objective–stage–metric–action mapping.'),[R('w1',32,35)],['w1-evaluate','w2-journey'], '目标 漏斗 点击 曝光 转化 留存 KPI funnel goals retention'),
F('media','concept','1',P('POE＋Category · 媒体分类','POE + Category · media classification'),P('把触点分成可管理的资源，而非一串平台名字。','Organize touchpoints into manageable resources, not platform names.'),P('规划渠道组合，或判断品牌能控制什么时。','When planning a channel mix or identifying brand control.'),[
 P('Paid · 付费：购买广告或传播。','Paid: purchased advertising or promotion.'),P('Owned · 自有：品牌掌握的内容和服务入口。','Owned: brand-controlled content and service.'),P('Earned · 赢得：消费者讨论、分享与口碑，可正可负。','Earned: discussion, sharing and word of mouth, positive or negative.'),P('Category · 品类：未提到本品牌且非本品牌发布的品类内容，包括竞争者内容。','Category: category content neither mentioning nor published by the focal brand, including competitor content.')],
 [P('逐个列出真实触点，再按活动的性质分类。','List real touchpoints and classify each activity.'),P('标出控制程度、投入和在旅程中的角色。','Mark control, investment and journey roles.'),P('决定需要增加广告、改善自有体验还是回应口碑。','Decide between advertising, owned-experience improvements and reputation responses.')],
 P('同一平台可承载多种媒体活动；不是万能分类，更不能把 earned 都当正面价值。','A platform may host multiple media activities; this is not universal, and earned attention may be negative.'),P('付费博主发帖是 paid；消费者自发转发产生的传播是 earned。','A paid influencer post is paid; voluntary customer sharing generates earned activity.'),
 [P('触点／具体活动','Touchpoint / activity'),P('媒体类别','Media category'),P('控制程度与成本','Control and cost'),P('旅程角色','Journey role'),P('缺口或风险','Gap or risk'),P('拟采取的行动','Proposed action')],P('一张媒体资源与控制边界地图。','A media-resource and control-boundary map.'),[R('w1',13,16)],['w1-evaluate','w2-social'], '渠道 媒体 资源 influencer 口碑 广告 owned paid earned competitors'),
F('journey','concept','2',P('客户旅程与全渠道','Customer journey & omnichannel'),P('看整条旅程，不把成交渠道当全部贡献。','Inspect the journey, not only the closing channel.'),P('手机、网站、门店结果不一致，或路径断裂时。','When mobile, web and stores disagree or journeys are fragmented.'),[
 P('触点角色：引入、辅助、完成目标。','Touchpoint roles: introduction, assistance and conversion.'),P('跨渠道连接：多渠道并存不等于体验协同。','Channel connection: coexistence does not imply coordination.'),P('Carryover · 延续：影响在后续阶段继续。','Carryover: effects persist into later stages.'),P('Spillover · 溢出：一个渠道影响另一渠道。','Spillover: one channel affects another.')],
 [P('按任务和时间画出接触、设备、渠道与结果。','Map tasks, times, contacts, devices, channels and outcomes.'),P('标记身份、窗口与线下记录的断点。','Mark identity, window and offline-data gaps.'),P('优先修复交接，并核对全渠道结果。','Repair handoffs and inspect omnichannel outcomes.')],
 P('合理的旅程故事仍不是贡献证明；连接信息还要考虑隐私和成本。','A plausible journey story is not contribution proof; linkage also has privacy and cost boundaries.'),P('手机查库存、店里体验、电脑下单：低手机 CVR 不自动等于低手机价值。','Mobile stock search, store trial and desktop checkout: low mobile CVR does not imply low mobile value.'),
 [P('顾客任务','Customer task'),P('按时间排列的触点与设备','Ordered contacts and devices'),P('每个触点的角色','Roles of contacts'),P('观察不到的路径','Unobserved path segments'),P('全渠道目标结果','Omnichannel outcome'),P('交接改进与验证','Handoff change and validation')],P('一张带断点和证据缺口的旅程地图。','A journey map with handoffs and evidence gaps.'),[R('w2',3,7),R('w2',15,21)],['w2-journey','w6-mobile'], '路径 门店 手机 设备 omnichannel mobile carryover spillover webrooming showrooming'),
F('brand-identity','concept','2',P('企业品牌身份九要素矩阵','Corporate brand identity matrix'),P('检查品牌核心、内部能力和外部承诺是否一致。','Check consistency of brand core, internal capabilities and external promises.'),P('内容方向混乱，或品牌承诺与体验不一致时。','When content lacks direction or promises differ from experience.'),[
 P('价值主张','Value proposition'),P('关系','Relationships'),P('定位','Position'),P('表达','Expression'),P('品牌核心','Brand core'),P('个性','Personality'),P('使命与愿景','Mission and vision'),P('文化','Culture'),P('能力','Competences')],
 [P('先说明品牌核心：承诺什么、依据什么价值。','Define the core promise and values.'),P('填写外部、内部和连接两者的要素，保留证据。','Populate external, internal and bridging elements with evidence.'),P('找出不一致，再决定内容、服务或能力建设的优先级。','Identify inconsistencies before prioritizing content, service or capability changes.')],
 P('填满九格不等于品牌有效；每格需要真实依据，矩阵不是因果检验。','Nine filled cells do not establish an effective brand; each needs evidence, and the matrix is not causal testing.'),P('品牌承诺“省时”，但服务能力导致排队：不能仅靠更快节奏的广告解决。','A time-saving promise conflicts with long service queues; faster-paced ads cannot alone fix it.'),
 [P('品牌核心／承诺及依据','Brand core / promise and evidence'),P('价值主张、关系、定位','Value proposition, relationships, position'),P('表达方式、个性','Expression and personality'),P('使命愿景、文化、能力','Mission/vision, culture, competences'),P('不一致与证据缺口','Inconsistencies and evidence gaps'),P('优先调整什么、怎样验证','Priority change and validation')],P('一张九要素一致性诊断矩阵。','A nine-element consistency diagnosis.'),[R('w2',27)],['w2-social'], '品牌 身份 定位 使命 文化 value proposition corporate identity matrix'),
F('emotion-wheel','concept','3',P('Plutchik · 情绪轮','Plutchik · emotion wheel'),P('把“正面／负面”拆成更具体的情绪和强度。','Distinguish specific emotions and intensity beyond positive/negative.'),P('两条负面评论需要不同回应，或分析表达机制时。','When negative comments need different responses or expression mechanisms matter.'),[
 P('喜悦 ↔ 悲伤','Joy ↔ sadness'),P('信任 ↔ 厌恶','Trust ↔ disgust'),P('恐惧 ↔ 愤怒','Fear ↔ anger'),P('惊讶 ↔ 期待','Surprise ↔ anticipation')],
 [P('先读对象、上下文、否定和讽刺。','Read targets, context, negation and sarcasm.'),P('用情绪类别与强度提出候选解释。','Use categories and intensity for candidate interpretations.'),P('用原文和人工检查核验，再连接回应或内容测试。','Validate against source text and human review before response or content testing.')],
 P('情绪轮是概念模型，不是心理真值检测器；语言和情境可能有歧义。','The wheel is a conceptual model, not a psychological truth detector; language and context can be ambiguous.'),P('“太失望了”和“我很愤怒”都可能是负面，却不必用同一种回应。','Disappointment and anger may both be negative but need not receive the same response.'),
 [P('原文与情境','Source text and context'),P('评价对象','Evaluation target'),P('候选情绪及强度','Candidate emotion and intensity'),P('支持／反驳线索','Supporting / opposing cues'),P('仍不确定的部分','Remaining uncertainty'),P('回应或测试建议','Response or test proposal')],P('有原文依据、保留歧义的情绪解读。','An evidence-linked emotion interpretation with ambiguity retained.'),[R('w3',8,9)],['w3-expression','t2b-text'], '情绪 愤怒 悲伤 恐惧 信任 emotion plutchik valence intensity sentiment'),
F('automation-augmentation','concept','AI',P('自动化—增强悖论','Automation–augmentation paradox'),P('判断哪些工作交给 AI，哪些需要人机共同完成。','Decide which work to automate and which to augment collaboratively.'),P('设计 AI 营销流程或分配审核责任时。','When designing AI marketing workflows and review responsibilities.'),[
 P('Automation · 自动化：机器接替人的任务。','Automation: machines take over a human task.'),P('Augmentation · 增强：人和机器紧密协作。','Augmentation: humans work closely with machines.'),P('两者跨时间与情境相互依赖，也存在张力；过度强调任一方可能产生问题。','The approaches are interdependent across time/context and involve tension; overemphasizing either can create problems.')],
 [P('把任务拆开，说明每步的风险与责任。','Decompose the task with risks and responsibilities.'),P('分别考虑替代、协作与人工保留的可能。','Consider replacement, collaboration and retained human work.'),P('评价整个流程的质量、效率和错误后果。','Evaluate workflow quality, efficiency and consequences.')],
 P('不能把自动化等同于效率提升；高风险动作仍需明确权限与审核。','Automation is not guaranteed efficiency; high-risk actions still need authority and review.'),P('AI 草拟客服回复，人核验政策并决定是否承诺退款。','AI drafts a service response; a person verifies policy and refund authority.'),
 [P('任务与最终责任人','Task and accountable person'),P('可自动化步骤','Potential automation steps'),P('需人机协作步骤','Collaboration steps'),P('错误后果与审核门槛','Error consequences and review gates'),P('质量与效率比较','Quality and efficiency comparison'),P('保留、调整或停止的条件','Conditions to retain, revise or stop')],P('一份可核验的人机分工方案。','A verifiable human–AI division of work.'),[R('genai',7)],['genai-workflow','guest-ai'], 'AI 人工 审核 替代 协作 automation augmentation agent workflow'),
F('influence','model','2',P('社会影响与 influencer 模型','Social influence & influencer models'),P('解释传播能力，而不只比较粉丝数量。','Explain diffusion potential beyond follower counts.'),P('选择 influencer 或评估社交传播时。','When selecting influencers or assessing diffusion.'),[
 P('Threshold rule · 阈值规则：何时一个人开始跟随。','Threshold rules: when someone starts following.'),P('Network · 网络：哪些人连接，连接到哪一层。','Network: connections and their levels.'),P('Dynamics · 动态：采用和分享怎样随时间传播。','Dynamics: adoption/sharing over time.'),P('层级粉丝规模与各层分享概率。','Follower counts by level and sharing probabilities.')],
 [P('确认目标受众、网络层级和传播任务。','Define audience, network levels and diffusion objectives.'),P('核查活跃度、分享概率及重叠，而非只取总粉丝。','Inspect activity, sharing likelihood and overlap, not just totals.'),P('以实际传播与目标结果验证选择。','Validate against actual diffusion and objective outcomes.')],
 P('网络传播潜力不等于销售增量；分享概率不能用无依据的假设替代。','Diffusion potential is not sales lift; sharing probabilities require evidence.'),P('小型创作者可能有活跃相关网络；大型账号可能大量粉丝不活跃。需数据比较，不能预判赢家。','A smaller creator may have an active relevant network and a larger one inactive followers; data are needed to choose.'),
 [P('目标人群与传播任务','Audience and diffusion task'),P('候选网络与层级','Candidate networks and levels'),P('活跃／分享概率依据','Activity / sharing evidence'),P('重叠及不确定性','Overlap and uncertainty'),P('传播与业务结果指标','Diffusion and business outcomes'),P('小范围验证方式','Small-scale validation')],P('一份以网络证据为依据的候选比较。','A network-evidence-based candidate comparison.'),[R('w2',28,29)],['w2-social'], 'influencer 传播 粉丝 分享 influence network threshold social proof virality'),
F('topic-journey','decision','3',P('主题 × 情感 × 旅程','Topic × sentiment × journey'),P('找到消费者在哪个环节、对什么不满意。','Locate what consumers dislike and where in the journey.'),P('总体评分或情感均值掩盖具体痛点时。','When overall ratings or sentiment hide specific issues.'),[
 P('Topic · 主题：在谈什么对象？','Topic: what is being discussed?'),P('Sentiment / emotion · 情感：怎样评价？','Sentiment / emotion: how is it evaluated?'),P('Journey stage · 旅程阶段：问题发生在哪里？','Journey stage: where does the issue occur?')],
 [P('保留原文与 ID，定义主题和阶段。','Retain text and IDs; define topics and stages.'),P('检查标签质量，再按主题和阶段汇总情感。','Validate labels before aggregating by topic and stage.'),P('结合严重性、频率和成本提出改善测试。','Propose improvement tests using severity, frequency and cost.')],
 P('交叉表支持诊断，不证明该主题造成评分变化；评论者也不代表全部顾客。','Cross-tabs aid diagnosis, not causality; reviewers are not all customers.'),P('位置好、入住慢：总情感近中性仍可隐藏入住环节的负面问题。','Good location and slow check-in: neutral overall sentiment can hide a check-in problem.'),
 [P('原文／记录 ID','Text / record ID'),P('主题及定义','Topic and definition'),P('阶段与分类依据','Stage and classification evidence'),P('情感／情绪及核验','Sentiment / emotion and validation'),P('频率、严重性、业务关联','Frequency, severity, business association'),P('改善假设与测试','Improvement hypothesis and test')],P('一张可追溯的旅程痛点表。','A traceable journey-pain-point table.'),[R('w3',10,11),R('t2b',14,15)],['t2b-text','w4-reviews'], '评论 痛点 文本 服务 主题 topic sentiment pain points review journey'),
F('search-mix','decision','4',P('SEO／SEA · 搜索组合','SEO/SEA · search mix'),P('按搜索意图、时间目标和最终价值配置自然与付费搜索。','Allocate organic and paid search by intent, horizon and value.'),P('决定内容建设、搜索广告或两者组合时。','When choosing content investment, search ads or their mix.'),[
 P('Search intent · 搜索意图：用户想完成什么任务？','Search intent: which task is the user pursuing?'),P('SEO · 自然搜索相关性与可访问性建设。','SEO: organic relevance and accessibility.'),P('SEA · 付费搜索的关键词、广告与落地页。','SEA: paid keywords, ads and landing pages.'),P('协同与替代：看总结果，不简单相加。','Synergy and substitution: inspect totals, not simple sums.')],
 [P('解释查询意图与目标时限。','Interpret query intent and objective horizon.'),P('匹配信息、广告与页面承接任务。','Match information, ads and page tasks.'),P('比较最终结果、成本及自然／付费替代。','Compare outcomes, costs and organic/paid substitution.')],
 P('这是从课件综合的决策视角，不是命名的新理论；课程排名和拍卖说明不是实时规则。','This is a synthesized decision lens, not a newly named theory; course rankings/auctions are not live rules.'),P('临近开课可测试报名词广告，长期课程指南服务探索；仍需看总报名与成本。','Near-start enrollment ads can be tested while lasting guides support exploration; inspect total enrollment and costs.'),
 [P('查询与意图证据','Query and intent evidence'),P('目标时限','Objective horizon'),P('SEO 与 SEA 分工','SEO/SEA roles'),P('广告—页面匹配','Ad–page fit'),P('总转化、成本与替代','Total conversions, cost and substitution'),P('拟测试的组合','Proposed mix test')],P('一份有条件的搜索组合建议。','A qualified search-mix proposal.'),[R('w4',23,25),R('w4',30),R('w4',48,51)],['w4-search'], '搜索 关键词 SEO SEA 广告 排名 自然 流量 search intent organic paid'),
F('ad-pricing','decision','5',P('广告计费与风险分配','Ad pricing & risk allocation'),P('统一计费分母，判断成本和风险落在哪里。','Normalize billing denominators and locate costs/risks.'),P('比较 CPM、CPC、CPA 报价或评价广告经济性时。','When comparing CPM/CPC/CPA quotes or ad economics.'),[
 P('CPM · 按千次展示付费。','CPM: payment per thousand impressions.'),P('CPC · 按点击付费。','CPC: payment per click.'),P('CPA · 按定义的转化／行动付费。','CPA: payment per defined action/conversion.'),P('后续行为风险与最终经济价值。','Downstream behavior risk and economic value.')],
 [P('先确认计费事件与转化定义。','Define billing events and conversions.'),P('用一致漏斗折算每次结果成本。','Translate to common outcome costs using a consistent funnel.'),P('与新增贡献及全部相关成本比较。','Compare incremental contribution with relevant costs.')],
 P('便宜 CPA 不保证利润；CVR 分母与窗口须一致，归因购买不等于新增购买。','Low CPA does not guarantee profit; CVR denominators/windows must match, and credited purchases may not be incremental.'),P('课件算例：€5 CPM、0.1% CTR、点击后 2% CVR → €250／次销售。','Slide calculation: €5 CPM, 0.1% CTR, 2% post-click CVR → €250 per sale.'),
 [P('计费方式／事件','Billing basis / event'),P('实际花费和事件量','Spend and event counts'),P('CTR、CVR 的分母／窗口','CTR/CVR denominators / windows'),P('统一后的结果成本','Normalized outcome cost'),P('新增程度和贡献价值','Incrementality and contribution'),P('经济性判断及缺口','Economic judgment and gaps')],P('可比较的单位成本与风险说明。','Comparable unit costs and risk allocation.'),[R('w5',3,9)],['w5-pricing'], '费用 便宜 成本 CPM CPC CPA CTR CVR 风险 利润 cost pricing risk'),
F('targeting','decision','5',P('定向方式与个性化粒度','Targeting signals & granularity'),P('先确认信号来自哪里，再决定对谁、何时、怎样沟通。','Identify signal sources before choosing audience, timing and communication.'),P('比较语境、行为、再营销、位置或逐人个性化时。','When comparing contextual, behavioral, retargeting, geographic or individual tailoring.'),[
 P('语境：当前内容与任务线索。','Contextual: content and task cues.'),P('行为：搜索、点击等历史行为。','Behavioral: past search, clicks and other actions.'),P('再营销：曾接触本品牌的人。','Retargeting: previous brand contacts.'),P('地理：位置和区域。','Geographic: location and area.'),P('分群／个体：细粒度增加成本与实施要求。','Segment/individual: finer tailoring adds costs and requirements.')],
 [P('把可用信号与真实意图分开。','Separate available signals from true intent.'),P('选择粒度与时机，写出机制假设。','Choose granularity/timing and state a mechanism hypothesis.'),P('用匹配问题的对照检验价值及负面体验。','Use a question-matched control to test value and harms.')],
 P('浏览不等于想买；更早、更细不自动更好。位置和数据使用许可需另核实。','Browsing is not intent; earlier/finer is not always better. Verify data/location permission separately.'),P('运动文章旁投鞋广告是语境定向；向本店浏览者追投是再营销。','A shoe ad beside sports content is contextual; follow-up to store browsers is retargeting.'),
 [P('信号及获取依据','Signal and acquisition basis'),P('目标人群／粒度','Audience / granularity'),P('时机与沟通内容','Timing and message'),P('机制与竞争解释','Mechanism and alternatives'),P('对照条件及最终结果','Control and final outcome'),P('成本、体验及数据边界','Cost, experience and data boundaries')],P('可检验的定向策略，而非“越个性化越好”。','A testable targeting strategy, not “more personal is better.”'),[R('w5',14,18),R('w5',19,22)],['w5-targeting'], '定向 个性化 再营销 retargeting contextual behavioral geographic segments personalization'),
F('recommender','decision','6',P('推荐机制分类与选择','Recommendation mechanisms'),P('按可用信息选择推荐依据，再评估整体价值。','Choose recommendation evidence from available information and evaluate value.'),P('给新用户、老用户或新商品设计推荐时。','When designing for new/returning users or new items.'),[
 P('Content-based · 基于内容：根据物品属性寻找相似物品；相似性的定义可能遗漏真实偏好。','Content-based: find similar items from attributes; the similarity definition can miss actual preferences.'),P('Collaborative · 协同过滤：根据用户／物品互动寻找相似行为；稀疏和冷启动会限制它。','Collaborative: find behavioral similarities from user/item interactions; sparsity and cold start constrain it.'),P('Hybrid · 混合：组合不同推荐依据；第 12 页的 Meta-path（元路径）是具体实现，不是所有混合方法的统一结构。','Hybrid: combine recommendation approaches; the meta-path method on p.12 is one implementation, not a universal hybrid structure.')],
 [P('先确认目标、物品属性、兴趣锚点及用户／物品互动是否可用。','Check the objective, item attributes, interest anchors and available user/item interactions.'),P('属性与兴趣锚点可支持内容推荐候选；可比互动支持协同候选；互补信息支持评估混合。都是待测试候选，不是自动赢家。','Attributes/interest anchors support a content-based candidate; comparable interactions support collaborative candidates; complementary information supports evaluating hybrids. None is an automatic winner.'),P('先与约定基线比较，再分开测试算法和呈现；检查价值、多样性、体验与成本。','Compare with an agreed baseline, then separate algorithm and presentation tests; inspect value, diversity, experience and cost.')],
 P('混合不保证解决冷启动；点击提升不等于准确率或全面业务改善。','Hybrids do not guarantee solved cold start; more clicks do not establish accuracy or overall improvement.'),P('新用户先给一本种子书，老用户用共同购买线索；两者均需验证。','A seed book helps new users; co-purchase signals help returning users. Both need validation.'),
 [P('推荐目标','Recommendation objective'),P('用户／物品已有信息','Available user/item information'),P('机制及理由','Mechanism and rationale'),P('稀疏／冷启动缺口','Sparsity / cold-start gaps'),P('推荐集合与呈现控制','Recommendation set and framing control'),P('价值、多样性与体验指标','Value, diversity and experience measures')],P('推荐机制选择与评估方案。','A mechanism-selection and evaluation plan.'),[R('w6',5,15)],['w6-recommend'], '推荐 商品 冷启动 多样性 collaborative content based hybrid recommender diversity'),
F('attribution','model','1',P('归因模型 · 分配信用','Attribution · allocate credit'),P('说明触点获得多少信用，以及规则如何影响它。','Explain touchpoint credit and how allocation rules affect it.'),P('平台都声称带来订单，或末次点击偏向收尾时。','When platforms claim the same orders or last-click favors closing.'),[
 P('规则型：首次、末次、线性、位置、时间衰减。','Rule-based: first, last, linear, position and time decay.'),P('数据驱动：利用已观察路径和模型。','Data-driven: observed journeys and models.'),P('窗口、身份、顺序与 baseline · 基线影响解释。','Windows, identity, order and baseline affect interpretation.')],
 [P('确认转化、观察窗口与去重。','Define conversions, windows and deduplication.'),P('写清分配规则或模型假设。','State rules or model assumptions.'),P('报告信用与敏感性；增量结论另需可信设计。','Report credit and sensitivity; incrementality needs credible identification.')],
 P('归因信用不等于因果效果；多个模型一致也可能共享偏差。','Credit is not causality; agreeing models may share biases.'),P('社交→邮件→搜索：末次点击全给搜索，但不能证明社交没有帮助。','Social→email→search: last-click credits search without proving social is useless.'),
 [P('转化定义、窗口与去重','Conversion, window and deduplication'),P('可见／不可见触点','Observed / missing contacts'),P('规则／模型与假设','Rules / model and assumptions'),P('信用分配结果','Credit allocation'),P('敏感性与缺口','Sensitivity and gaps'),P('要识别增量还需什么','Further evidence for incrementality')],P('一份有限定条件的信用分配解释。','A qualified credit-allocation interpretation.'),[R('w1',43,58),R('t1',42,45)],['w1-evaluate','t1-regression'], '归因 渠道 信用 重复 订单 last first click attribution credit paths'),
F('mmm','model','2',P('MMM · 营销组合模型','MMM · marketing mix modeling'),P('用聚合数据分析媒体投入与总体销售的关系。','Relate media investment to total sales using aggregate data.'),P('个体旅程不完整，且关注跨媒体、时间和预算时。','When individual journeys are incomplete and media, time and budgets matter.'),[
 P('聚合结果：销售等时间序列。','Aggregate outcomes: sales time series.'),P('媒体投入及其变化。','Media investment and variation.'),P('促销、季节、天气等控制因素。','Controls such as promotion, seasonality and weather.'),P('延迟、跨渠道关系与模型假设。','Delays, cross-channel relations and model assumptions.')],
 [P('把历史实际销售 Y、各媒体投入 X 与其他解释因素按时间对齐；没有实际结果就暂停拟合。','Align observed historical sales Y, media inputs X and other explanatory factors over time; without observed outcomes, stop before fitting.'),P('检查投入变化、遗漏因素与设定，再用实际 Y 拟合模型；拟合值不是观测值。','Inspect variation, omissions and specification, then fit against observed Y; fitted values are not observations.'),P('先报告有条件的关联／拟合与不确定性；预算调整还须核验模型假设和其他可信证据。','First report conditional association/fit and uncertainty; budget changes also need checked assumptions and other credible evidence.')],
 P('MMM 不是缺少个体数据时自动正确的因果替代；预算模拟依赖设定。','MMM is not an automatically causal replacement for missing individual data; simulations depend on assumptions.'),P('每周家具销售与广告、促销、季节一起分析，避免只把销售变化归给广告。','Analyze weekly furniture sales alongside media, promotion and seasonality, not advertising alone.'),
 [P('结果与时间粒度','Outcome and time granularity'),P('各媒体投入','Media investments'),P('控制因素与遗漏风险','Controls and omission risks'),P('模型设定及变化是否足够','Specification and available variation'),P('结果与不确定性','Results and uncertainty'),P('交叉验证／预算判断边界','Triangulation / budget boundaries')],P('聚合层级的媒体分析与有条件预算建议。','Aggregate media analysis and qualified budget proposals.'),[R('w2',8,12)],['w2-journey'], 'MMM 预算 销售 聚合 季节 promotion marketing mix modeling'),
F('regression','model','T',P('回归 · 变量到结果','Regression · variables to outcomes'),P('根据 Y 选模型，读对系数、比较与不确定性。','Choose from Y and interpret coefficients, comparisons and uncertainty.'),P('判断哪些因素与金额、购买或互动相关时。','When examining associations with spending, purchase or engagement.'),[
 P('连续 Y：课程介绍线性回归。','Continuous Y: linear regression in the course.'),P('二元 Y：课程介绍逻辑回归。','Binary Y: logistic regression in the course.'),P('参照组、单位、交互与不确定性。','Reference groups, units, interactions and uncertainty.'),P('OR · 优势比不是概率倍数。','Odds ratios are not probability ratios.')],
 [P('明确 Y、X 与测量尺度，正确编码。','Define Y, X and scales; encode correctly.'),P('结合方向、大小、参照组与交互读结果。','Read direction, size, reference and interactions together.'),P('区分关联、预测与因果，说明证据缺口。','Separate association, prediction and causality; state gaps.')],
 P('显著不等于业务重要或因果；不显著也不证明没有作用。','Significance is not importance or causality; non-significance does not prove no effect.'),P('假设基准概率 20%、OR=2，概率约为 33.3%，不是 40%。','With hypothetical baseline probability 20% and OR=2, probability is about 33.3%, not 40%.'),
 [P('Y 的定义与尺度','Y definition and scale'),P('X、编码、参照组','X, coding and reference'),P('系数尺度及交互','Coefficient scale and interactions'),P('大小与不确定性','Magnitude and uncertainty'),P('混淆／遗漏与识别限制','Confounding / omission and identification limits'),P('支持什么、不支持什么','Supported and unsupported claims')],P('一份不夸大结论的模型解释。','A calibrated model interpretation.'),[R('t1',10,35)],['t1-regression','w2-social'], '回归 系数 显著 交互 虚拟变量 logistic linear odds ratio dummy interaction'),
F('experiment','model','5',P('A/B 与增量检验','A/B testing & incrementality'),P('让对照条件匹配你真正想判断的改变。','Match controls to the change you want to evaluate.'),P('判断改动是否有效，或广告是否带来新增结果时。','When evaluating a change or advertising lift.'),[
 P('问题与处理：究竟改变什么？','Question and treatment: what changes?'),P('随机分配与对照。','Random assignment and controls.'),P('最终结果、成本和不确定性。','Final outcomes, cost and uncertainty.')],
 [P('指定问题、随机分配单位与对照条件。','Specify question, assignment unit and control.'),P('预先定义结果与评估窗口，检查干扰。','Define outcomes/windows and inspect interference.'),P('比较差异、精度与经济价值，再决定是否扩展。','Compare differences, precision and economics before scaling.')],
 P('随机分配不等于随机抽样；两个广告版本的比较不等于有／无广告增量。','Assignment is not sampling; comparing two ads is not ads-versus-no-ads lift.'),P('测试“再营销是否新增购买”需要无再营销对照，而不只是文案 A 对 B。','Testing retargeting lift requires a no-retargeting control, not only copy A versus B.'),
 [P('待检验问题与改变','Question and change'),P('随机单位及人群','Assignment unit and population'),P('处理／对照条件','Treatment / control'),P('结果、窗口与数据质量','Outcomes, window and quality'),P('差异、不确定性及成本','Difference, uncertainty and costs'),P('扩大、调整或停止的条件','Scale, revise or stop conditions')],P('一份问题匹配的实验方案和有边界的判断。','A question-matched test plan and bounded judgment.'),[R('w5',16,17)],['w5-targeting','recap-reason'], '实验 AB A/B 对照 因果 增量 随机 holdout randomization lift causal test')
];

/* Application gates are editorial teaching checks, not universal theory thresholds. */
const G=(need,proceed,stop,challenge)=>({need,proceed,stop,challenge,basis:'editorial'});
const gates={
 race:G(P('业务目标、受众、阶段及可比较的指标定义。','Objective, audience, stage and comparable metric definitions.'),P('可定位阶段缺口并提出验证；阶段指标不直接证明总业务改善。','Locate stage gaps and propose a test; stage metrics do not establish overall business improvement.'),P('目标、分母或窗口不清，先补定义，不排名渠道。','If goals, denominators or windows are unclear, define them before ranking channels.'),P('局部指标上升而下游结果下降，会反驳这项优化。','A local metric gain with worse downstream outcomes challenges the change.')),
 media:G(P('具体媒体活动、发布者、付费关系和是否提到本品牌。','Specific activity, publisher, payment relationship and focal-brand mention.'),P('可分类活动与控制边界；投入建议还需目标、成本和结果。','Classify activities/control; investment advice also needs goals, cost and outcomes.'),P('只有平台名字或不知是否付费，暂不定类。','A platform name or unknown payment status is insufficient for classification.'),P('同一平台上的不同活动可能属于不同类别。','Different activities on one platform can belong to different classes.')),
 journey:G(P('触点任务、时间顺序、设备／渠道及可见路径。','Touchpoint tasks, sequence, devices/channels and observed paths.'),P('可定位交接问题；贡献或增量要另外检验。','Locate handoff issues; contribution/lift requires a separate test.'),P('无法连接身份或线下路径时，保留断点，不补成真实路径。','If identity/offline paths cannot be linked, retain gaps rather than invent a journey.'),P('别的路径或线下成交可能推翻只看收尾渠道的解释。','Alternative paths/offline sales can challenge a closing-channel explanation.')),
 'brand-identity':G(P('九格的品牌文件、真实表达、服务体验或能力证据。','Brand documents, actual expression, experiences or capability evidence for the cells.'),P('可指出不一致并提出改善方向，不可由填表证明品牌有效。','Identify inconsistencies and improvement directions, not effectiveness from a filled matrix.'),P('只有宣传口号没有实际证据，相关格保留待核实。','If only slogans are available, mark unsupported cells unverified.'),P('顾客体验或内部能力与承诺相反，是关键反证。','Experiences/capabilities contradicting the promise are key counterevidence.')),
 'emotion-wheel':G(P('评论原文、对象、上下文与候选情绪依据。','Original text, target, context and evidence for a candidate emotion.'),P('可提出并核验情绪解释，不自动判断心理真值。','Propose/validate an interpretation, not automatically infer psychological truth.'),P('讽刺、否定或对象不清，先人工核验，不自动回应。','Review unclear irony, negation or targets before responding automatically.'),P('另一种语境解释能否同样解释这段原文？','Could another contextual interpretation explain the same text?')),
 'automation-augmentation':G(P('任务流程、跨步骤依赖、权限、质量和人工责任。','Workflow, cross-task dependencies, authority, quality and human accountability.'),P('可比较分工方案并设计小范围验证；不能声称已复现论文完整机制。','Compare workflow arrangements and design a small test, not claim the full paper mechanism is established.'),P('论文全文机制待核实；流程依赖或责任不清时，不推出自动化最优。','Full-paper mechanisms remain unverified; unclear dependencies/accountability do not support optimal automation.'),P('单步提效却让整个流程质量下降，会反驳该分工。','A faster step with worse overall quality challenges that arrangement.')),
 influence:G(P('目标受众、网络层级、实际活跃／分享与重叠记录。','Audience, network levels, observed activity/sharing and overlap.'),P('可比较传播候选；销售增量须独立证据。','Compare diffusion candidates; sales lift needs independent evidence.'),P('只有粉丝数、没有传播概率或去重依据，不估算有效触达。','Follower counts without sharing/deduplication evidence do not support effective reach estimates.'),P('受众不相关、重复触达或不活跃可能推翻大账号优先。','Irrelevance, duplication or inactivity can challenge a large-account preference.')),
 'topic-journey':G(P('原文 ID、主题／阶段定义、标签核验及各格样本数。','Text IDs, topic/stage definitions, validated labels and cell counts.'),P('可定位有证据的痛点并提出改善测试，不宣称主题造成结果。','Locate evidenced pain points and propose tests, not claim the topic caused an outcome.'),P('空格或小样本不足时标待核实，不把空白当没有问题。','Mark missing/insufficient cells unverified; blank cells are not absence of a problem.'),P('标签误判、评论者偏差或阶段混淆会改变痛点排序。','Coding error, reviewer selection or stage confusion can change pain-point priorities.')),
 'search-mix':G(P('查询意图、目标时限、自然／付费基线、成本与最终结果。','Query intent, horizon, organic/paid baselines, cost and final outcomes.'),P('可提出组合测试；定性曲线不能推算预算比例或必然效果。','Propose a mix test; qualitative curves cannot calculate budget shares or guaranteed effects.'),P('未说明投入是否持续、效果指什么或替代关系，不推出最优组合。','Unspecified investment continuity, outcome definition or substitution does not establish an optimal mix.'),P('付费转化上升而总转化不变，可能是替代而不是增量。','More paid conversions with unchanged totals may indicate substitution, not lift.')),
 'ad-pricing':G(P('计费事件、花费、CTR／CVR 分母窗口与每次结果贡献。','Billing event, spend, CTR/CVR denominators/windows and outcome contribution.'),P('可统一单位成本；利润判断还需新增程度与全部相关成本。','Normalize unit costs; profit also needs incrementality and relevant costs.'),P('转化定义、分母或贡献价值不清，不宣布 CPA 便宜或盈利。','Unclear conversions, denominators or value do not support cheap/profitable CPA claims.'),P('低 CPA 却来自低价值或非新增行动，会反驳经济性判断。','Low CPA from low-value/nonincremental actions challenges economic value.')),
 targeting:G(P('信号来源、目标粒度、触达时机及匹配问题的对照。','Signal sources, granularity, timing and a question-matched control.'),P('可设计定向测试；更细粒度必须用净价值与体验验证。','Design a targeting test; finer granularity needs net-value/experience validation.'),P('信号权限、真实意图或对照不清，不宣称定向产生增量。','Unclear authority, intent or control does not support targeting-lift claims.'),P('购买原本就会发生、过早打扰或成本增加均可推翻建议。','Purchases that would occur anyway, premature contact or extra cost can challenge the proposal.')),
 recommender:G(P('物品属性、兴趣锚点、用户／物品互动、候选基线与评价目标。','Item attributes, interest anchors, interactions, candidate baseline and evaluation objective.'),P('按信息提出内容／协同／混合候选；同条件比较后才讨论优先。','Propose content/collaborative/hybrid candidates from information; compare under consistent conditions before prioritizing.'),P('没有有效兴趣线索或可比互动时，先补材料；不凭“混合”二字宣称更好。','Without usable interest cues/comparable interactions, gather evidence; the hybrid label alone does not imply superiority.'),P('属性与偏好不符、冷启动失败或多样性／净价值下降会反驳推荐选择。','Attribute/preference mismatch, cold-start failure or worse diversity/net value can challenge selection.')),
 attribution:G(P('转化定义、可观察触点、窗口、身份去重与分配规则。','Conversion definition, observable contacts, window, deduplication and credit rule.'),P('可报告规则内信用及敏感性；不能直接转成因果预算建议。','Report rule-based credit/sensitivity, not direct causal budget advice.'),P('触点缺失或多平台重复归功时，先核验，不加总成增量。','Check missing contacts/duplicate platform credit; do not sum them as lift.'),P('换窗口或规则就改变赢家，说明结论依赖规则。','A different winner after changing window/rule indicates rule dependence.')),
 mmm:G(P('同时间粒度的实际销售 Y、媒体投入 X、其他因素及足够的投入变化。','Aligned observed sales Y, media inputs X, other factors and usable input variation.'),P('可拟合并报告有条件的关联与不确定性；预算改变还需验证设定和其他证据。','Fit/report conditional associations and uncertainty; budget changes additionally need checked specification and other evidence.'),P('缺少实际 Y、关键因素或可用变化时，暂停贡献估计与预算最优判断。','Without observed Y, key factors or usable variation, pause contribution/optimal-budget claims.'),P('遗漏促销、投入随需求改变或结果对设定敏感，都可能反驳贡献解释。','Omitted promotions, demand-responsive spend or specification sensitivity can challenge contribution interpretations.')),
 regression:G(P('Y／X 定义、编码、参照组、数据结构及模型结果。','Y/X definitions, coding, reference groups, data structure and model results.'),P('可解释模型内关联；预测要验证，因果要有识别依据。','Interpret within-model association; prediction needs validation and causality needs identification.'),P('测量、编码、设定或数据质量未核验，不只凭显著性给建议。','Unverified measurement, coding, specification or quality rules out significance-only advice.'),P('改变参照、加入遗漏因素或检查交互后，解释是否仍成立？','Does the interpretation survive reference changes, omitted-factor checks or interactions?')),
 experiment:G(P('问题匹配的处理／对照、随机单位、结果窗口、数据质量与判断标准。','Question-matched treatment/control, assignment unit, outcome window, quality and decision criteria.'),P('可比较效果与不确定性；净价值、实施风险和外推条件支持后续行动。','Compare effects/uncertainty; net value, implementation risk and generalizability inform action.'),P('对照不匹配、严重干扰或精度不足时，不宣布无效或扩大投放。','With mismatched controls, serious interference or inadequate precision, do not declare no effect or scale.'),P('脱落、组间干扰或成本抵消效果，可能推翻扩大建议。','Attrition, interference or costs offsetting effects can challenge scaling.'))
};
for(const f of DMA.frameworks)f.gate=gates[f.id];
const section=(title,body,basis,refs=[],flow=[])=>({title,body,basis,refs,flow});
const byId=id=>DMA.frameworks.find(f=>f.id===id);
byId('mmm').notes=[section(P('先区分实测和拟合','Separate observations from fit'),P('历史 Y 是实测销售，拟合值 Ŷ 是模型对 Y 的解释／预测。第 9 页区分结果与解释变量；第 10 页说明回归用途。由“拟合不错”到“改变预算会新增销售”仍有识别与验证缺口。最后这项提醒是教学分析，不是课件给出的自动预算规则。','Historical Y is observed sales; fitted Ŷ is the model’s explanation/prediction. Page 9 distinguishes outcomes and explanatory variables; p.10 describes regression. Good fit does not establish sales lift from budget changes. That final caution is editorial analysis, not a slide automatic-budget rule.'),'source-analysis',[R('w2',9,10)])];
byId('recommender').notes=[section(P('一个混合实现：Meta-path（元路径）','One hybrid implementation: meta-paths'),P('第 12 页介绍在异质信息网络中结合用户反馈、物品／用户属性和关系，利用元路径建模偏好。下列结构只帮助理解这一个实现；不是所有混合方法都必须有这三类输入，也不说明固定权重。算法与路径选择的细节仍需指定阅读。','Page 12 describes combining feedback, item/user attributes and relations in a heterogeneous information network to model preferences with meta-paths. The flow below explains this implementation only; not every hybrid requires these inputs or fixed weights. Algorithm/path-selection details require the designated reading.'),'source',[R('w6',12)],[P('反馈、属性与关系','Feedback, attributes & relations'),P('提取／选择元路径','Extract / select meta-paths'),P('偏好建模','Preference modeling')])];
byId('automation-augmentation').gap=P('解释层级：课件定义与摘要。论文完整机制、循环条件仍待核实。','Explanation level: slide definitions/abstract. Full-paper mechanisms and cycle conditions remain unverified.');
byId('automation-augmentation').notes=[
 section(P('课件已支持什么？','What do the slides support?'),P('第 7 页的定义区分机器接替任务与人机协作。所嵌摘要进一步指出：两者跨时间与空间相互依赖，过度强调任一方可能形成负面强化循环；更广的视角有助于处理张力与互补。这是摘要层级主张，不是已核实的完整机制。','Page 7 distinguishes task replacement from human–machine collaboration. Its embedded abstract describes interdependence across time/space, possible negative reinforcing cycles from overemphasis, and a broader perspective for tensions/complementarity. These are abstract-level claims, not a verified full mechanism.'),'source',[R('genai',7)]),
 section(P('为什么不能只做一次二选一？','Why not a single either/or decision?'),P('教学分析：一个步骤的替代可能改变其他步骤需要人做什么，所以评价单位应覆盖流程与时间。假设文本处理先由 AI 辅助人核验，再将稳定的重复部分自动处理，异常仍交回人机协作。这个例子说明可能的依赖，不是论文实证、必经循环或普遍最优方案。','Editorial analysis: replacing one step can change what people must do elsewhere, so assess workflow/time. Hypothetical text processing: AI-assisted human review, then automation of stable repetition, with exceptions returned to collaboration. This illustrates possible dependencies, not paper evidence, a mandatory cycle or universal optimum.'),'example',[],[P('人机核验','Human–AI review'),P('重复部分自动处理','Automate stable repetition'),P('异常交回协作','Return exceptions to collaboration')]),
 section(P('材料缺口与不能推出的结论','Evidence gaps and unsupported conclusions'),P('未核实论文全文，不能补写强化循环的具体成因、阶段、条件或最佳管理处方。应用时还需流程依赖、质量变化与责任记录；目前只可提出待检验的分工假设，不能宣布自动化或增强一定更优。','Without verified full text, do not invent reinforcing-cycle causes, stages, conditions or management prescriptions. Application also needs workflow dependencies, quality changes and accountability records. Currently propose testable arrangements, not guaranteed superiority of automation or augmentation.'),'gap')
];
DMA.frameworkReview={date:'2026-10-03',repaired:['mmm','recommender','automation-augmentation'],scope:P('修补已定位漏洞并加入应用检查；不代表所有框架或五步链已完成全面逻辑审计。','Repairs identified gaps and adds application checks; not an exhaustive logical audit of every framework or five-step chain.'),automatedChecks:P('自动检查验证字段、链接与来源范围，不验证推理必然成立。','Automated checks validate fields, links and source ranges, not logical entailment.')};
})();
