/* Source-grounded redraws and explicitly labeled teaching examples. No invented quadrants. */
window.DMAFrameworkVisuals={create({bi,esc,getLang}){
const P=(zh,en)=>[zh,en];
const N=(x,y,label,explain,part=null)=>({x,y,label,explain,part});
const diagrams={
 race:{kind:'race-plan',label:P('先规划，再管理 RACE 阶段','Plan before managing RACE stages'),note:P('恢复课件中的 Plan、四阶段与回看提示；宽度不表示人数或转化率。回看属于营销管理，不表示顾客必须绕一圈。','Restores Plan, four stages and the slide’s revisit cue. Widths are not counts/rates; review is managerial, not a mandatory customer circuit.'),nodes:[
 N(47,10,P('Plan · 规划目标','Plan · set goals'),P('先明确业务目标、受众与策略，才能判断应该改善哪个阶段。','Define the business objective, audience and strategy before choosing a stage to improve.'),4),
 N(47,31,P('Reach · 触达','Reach'),P('让合适的人发现品牌；触达是过程信号，不能直接当作最终成果。','Help the right people discover the brand; reach is a process signal, not automatically the final result.'),0),
 N(47,49,P('Act · 互动与考虑','Act · interact'),P('从发现走向探索、比较与互动；这些行为不等于已经购买。','Move from discovery to exploration and comparison; interaction is not purchase.'),1),
 N(47,67,P('Convert · 转化','Convert'),P('完成已定义的目标行动，再按一致分母与窗口评价转化。','Complete the defined target action and evaluate it with consistent denominators/windows.'),2),
 N(47,85,P('Engage · 留存与关系','Engage · relationships'),P('检查复购、关系与推荐，再回看计划。真实顾客仍可跳跃或往返。','Inspect repeat buying, relationships and advocacy, then revisit the plan. Actual customers may skip or revisit stages.'),3)]},
 media:{kind:'hub',label:P('媒体资源生态图','Media resource map'),center:P('品牌触点','Touchpoints'),note:P('四类资源围绕触点组织，不表示固定顺序、比例或互斥的平台类别。','Four resource classes, not a sequence, proportions or mutually exclusive platforms.'),nodes:[
 N(23,23,P('Paid · 付费','Paid'),P('购买广告或传播；“在哪个平台”并不决定媒体类别。','Purchased promotion; platform alone does not determine category.'),0),
 N(77,23,P('Owned · 自有','Owned'),P('品牌掌握的内容和服务入口。','Brand-controlled content and service.'),1),
 N(23,77,P('Earned · 口碑','Earned'),P('自发讨论、分享与口碑，可能正面也可能负面。','Voluntary discussion and sharing may be positive or negative.'),2),
 N(77,77,P('Category · 品类','Category'),P('围绕品类、但未提到本品牌且非本品牌发布的内容，包括竞争者内容；不要等同于本品牌口碑。','Category content neither mentions nor is published by the focal brand, including competitor content; it is not focal-brand word of mouth.'),3)]},
 journey:{kind:'lanes',label:P('跨设备、跨渠道旅程','Cross-channel journey'),lanes:[P('手机','Mobile'),P('门店','Store'),P('电脑','Desktop')],note:P('假设路径，不是顾客数据；虚线表示可能的跨渠道联系，需另行验证。','Hypothetical journey, not customer data; dashed cross-channel links need verification.'),nodes:[
 N(25,22,P('查库存','Check stock'),P('手机可以承担探索和辅助角色，不能只看手机成交率。','Mobile may assist exploration; its conversion rate alone misses this role.'),0),
 N(51,50,P('体验商品','Try in store'),P('渠道交接是否顺畅，会影响整条旅程的体验。','Handoff quality affects the journey experience.'),1),
 N(78,78,P('完成下单','Order'),P('成交渠道不自动拥有全部贡献；故事仍不是贡献证明。','The closing channel does not own all contribution; a story is not proof.'),3),
 N(80,22,P('售后服务','Service'),P('购买后仍可能回到手机；这是补充的旅程示意。','A customer may return to mobile after purchase; an editorial illustration.'),1)]},
 'brand-identity':{kind:'brand',label:P('企业品牌身份矩阵','Corporate brand identity matrix'),note:P('九要素按课件位置重绘；连接线仅提示一致性检查，不表示因果方向。','Nine elements follow the slide layout; links prompt consistency checks, not causality.'),nodes:[
 N(20,20,P('价值主张','Value proposition'),P('给外部受众的价值，与品牌核心和实际能力是否匹配？','Does promised value fit the core and actual competences?'),0),
 N(50,20,P('关系','Relationships'),P('品牌希望建立什么关系？实际互动是否支持这种关系？','What relationship is intended, and do interactions support it?'),1),
 N(80,20,P('定位','Position'),P('希望相对其他选择处于什么位置？依据是什么？','What relative position is intended, and on what evidence?'),2),
 N(20,50,P('表达','Expression'),P('语言、视觉与行为是否表达同一个品牌核心？','Do language, visuals and behavior express the same core?'),3),
 N(50,50,P('品牌核心','Brand core'),P('核心承诺与价值，是检查另外八格一致性的参照。','The core promise and values anchor consistency checks.'),4),
 N(80,50,P('个性','Personality'),P('品牌呈现怎样的性格，是否与表达和承诺一致？','Does the brand personality fit expression and promises?'),5),
 N(20,80,P('使命与愿景','Mission & vision'),P('内部方向如何支持对外承诺？','How does internal direction support external promises?'),6),
 N(50,80,P('文化','Culture'),P('内部文化是否让员工能够兑现品牌承诺？','Does internal culture support delivering the promise?'),7),
 N(80,80,P('能力','Competences'),P('具备哪些兑现承诺的能力？不要用传播代替能力建设。','Which competences deliver the promise? Communication cannot replace capability.'),8)]},
 'emotion-wheel':{kind:'wheel',label:P('八种基本情绪与对立关系','Eight emotions and opposites'),center:P('情绪解读','Emotion'),note:P('简化情绪轮：只呈现八类及对立关系，不复制完整强度、混合情绪或原图配色。','Simplified wheel: eight categories/opposites, not the complete intensities, blends or original colors.'),nodes:[
 N(50,13,P('喜悦','Joy'),P('与悲伤相对；正面词不必然意味着真实的喜悦。','Opposite sadness; positive wording is not necessarily joy.'),0),
 N(77,24,P('信任','Trust'),P('与厌恶相对；检查评价对象与上下文。','Opposite disgust; check the target and context.'),1),
 N(88,50,P('恐惧','Fear'),P('与愤怒相对；回应应区分担忧与愤怒。','Opposite anger; responses should distinguish worry and anger.'),2),
 N(77,76,P('惊讶','Surprise'),P('与期待相对；惊讶不必然是正面或负面。','Opposite anticipation; surprise is not necessarily positive or negative.'),3),
 N(50,87,P('悲伤','Sadness'),P('与喜悦相对；具体语言仍需人工核验。','Opposite joy; specific language still needs review.'),0),
 N(23,76,P('厌恶','Disgust'),P('与信任相对；不能把所有负面表达都归为厌恶。','Opposite trust; not every negative expression is disgust.'),1),
 N(12,50,P('愤怒','Anger'),P('与恐惧相对；识别原因，不能只根据单个词贴标签。','Opposite fear; identify reasons, not just isolated words.'),2),
 N(23,24,P('期待','Anticipation'),P('与惊讶相对；保留语境和仍不确定的部分。','Opposite surprise; retain context and ambiguity.'),3)]},
 'automation-augmentation':{kind:'paradox',label:P('从单个任务，转向跨任务与时间的关系','From single tasks to cross-task/time relationships'),note:P('只解释第 7 页定义与摘要层级：两者跨时间与任务相互依赖；具体强化循环、发生条件和管理机制仍待全文核实。连线不是完整因果模型。','Definition/abstract level on p.7 only: interdependence across time/tasks. Detailed reinforcing cycles, conditions and management mechanisms await full-text verification; links are not a complete causal model.'),nodes:[
 N(25,24,P('自动化 · 机器接替','Automation · replacement'),P('Automation（自动化）：机器接替原本由人完成的任务。接替不自动等于整个流程更有效。','Automation: machines take over a human task. Replacement does not automatically improve the whole workflow.'),0),
 N(75,24,P('增强 · 人机协作','Augmentation · collaboration'),P('Augmentation（增强）：人和机器紧密协作；不是仅把自动化减到一半。','Augmentation: humans work closely with machines; it is not simply half as much automation.'),1),
 N(50,76,P('跨任务／时间看依赖','Dependencies across tasks / time'),P('课件摘要：两者不能清楚分离，跨时间与空间相互依赖；过度强调任一方可能引出负面强化循环。摘要支持这个主张，但不交代完整循环如何形成；详见下方“解释与缺口”。','Slide abstract: the approaches cannot be neatly separated and are interdependent across time/space; overemphasis can fuel negative reinforcing cycles. The abstract supports the claim, not a full account of those cycles; see explanation/gaps below.'),2)]},
 influence:{kind:'network',label:P('社会影响传播网络','Social diffusion network'),note:P('假设网络：连线不代表实测传播，节点大小不代表影响力；重叠受众要去重。','Hypothetical network: links are not observed diffusion, sizes are not influence; deduplicate overlap.'),nodes:[
 N(14,50,P('创作者','Creator'),P('粉丝总数只是起点，还要核查相关性、活跃度与传播概率。','Follower count is only a starting point; inspect relevance, activity and sharing.'),1),
 N(44,19,P('一层 A','Tier 1 A'),P('第一层受众可能分享，也可能不分享；概率需要证据。','A first-tier audience may or may not share; probabilities require evidence.'),3),
 N(44,50,P('一层 B','Tier 1 B'),P('两个节点可能触达同一受众，不能简单加总。','Nodes may reach the same audience; do not simply sum.'),1),
 N(44,81,P('一层 C','Tier 1 C'),P('采用行为取决于阈值与情境，不只取决于连接数量。','Adoption depends on thresholds and context, not just connections.'),0),
 N(81,19,P('二层 1','Tier 2 1'),P('第二层传播是动态过程，应跟踪时间与真实分享。','Second-tier diffusion is dynamic; track time and actual sharing.'),2),
 N(81,50,P('重叠受众','Overlap'),P('共同受众提示去重和传播饱和风险；这里没有估计人数。','Shared audiences signal deduplication/saturation; no audience counts are estimated.'),1),
 N(81,81,P('二层 2','Tier 2 2'),P('传播不是销售增量；业务结果仍要另行验证。','Diffusion is not sales lift; validate business outcomes separately.'),2)]},
 'topic-journey':{kind:'cross',label:P('把情感放回具体主题与阶段','Place sentiment in its topic and stage'),rows:[P('主题 A','Topic A'),P('主题 B','Topic B')],cols:[P('购买前','Before'),P('购买中','During'),P('购买后','After')],note:P('空白应用模板；主题与阶段是占位符，需按材料重定义。每格填写原文、数量和正负评价；缺少记录不等于没有痛点。','Blank application template: redefine placeholder topics/stages from evidence. Record text, counts and sentiment per cell; missing records are not absence of pain.'),nodes:[
 ...[34,72].flatMap((y,r)=>[30,57,84].map((x,c)=>N(x,y,P('＋ 证据','＋ Evidence'),P(`主题 ${r?'B':'A'}，${['购买前','购买中','购买后'][c]}：先找原文与记录 ID，再填写评论数量、情感分布和分类依据。没有材料就保留“待核实”。`,`Topic ${r?'B':'A'}, ${['before','during','after'][c]} purchase: retain text/IDs, comment counts, sentiment distribution and coding evidence. Mark missing evidence unverified.`))))]},
 'search-mix':{kind:'time-effects',label:P('SEO／SEA：时间与效果的定性差别','SEO/SEA: qualitative effects over time'),axes:[P('时间 →','Time →'),P('效果（定性）↑','Effect (qualitative) ↑')],miniAxes:[P('时间 →','Time →'),P('效果 ↑','Effect ↑')],note:P('按第 51 页的定性时间结构重绘，无数值刻度；不是效果预测、排名承诺或最优预算公式。实际速度与持续性依赖投入和情境。','Redraws the qualitative time structure on p.51 without numeric scales. Not a forecast, ranking guarantee or optimal-budget formula; timing/persistence depend on investment and context.'),nodes:[
 N(26,32,P('SEA · 较快起效','SEA · earlier effect'),P('SEA（搜索引擎广告）可较快获得付费展示，但持续效果依赖投放。不能由示意曲线推算转化或预算。','SEA (search engine advertising) can obtain paid visibility earlier; ongoing effects depend on advertising. The schematic cannot calculate conversions or budgets.'),2),
 N(73,51,P('SEO · 逐步积累','SEO · builds over time'),P('SEO（搜索引擎优化）通过内容、相关性与可访问性逐步建设自然展示。课件提出协同可能，但总效果不能简单相加。','SEO (search engine optimization) builds organic visibility through content, relevance and accessibility. The slide suggests synergy, not additive total effects.'),1)]},
 'ad-pricing':{kind:'pricing-compare',label:P('三种计费方式：并列选择，不是步骤','Three billing alternatives, not sequential steps'),note:P('按相同结果定义比较。课件讨论广告主风险从 CPM 到 CPA 转移；并不意味着 CPA 总是便宜，或必然产生新增利润。','Compare using the same outcome definition. The slides discuss advertiser risk shifting from CPM to CPA; CPA is not always cheaper or necessarily incremental profit.'),nodes:[
 N(18,26,P('CPM · 展示','CPM · impressions'),P('按千次展示付费：广告主承担后续点击与行动的不确定性。课件比较中广告主风险较高、发布方较低。','Pay per thousand impressions: the advertiser bears uncertainty about clicks/actions. The slide comparison puts more risk on advertiser, less on publisher.'),0),
 N(50,26,P('CPC · 点击','CPC · clicks'),P('按点击付费：发布方承担获得点击的风险，广告主仍承担点击后的行动风险。','Pay per click: publisher bears click-generation risk; advertiser still bears post-click action risk.'),1),
 N(82,26,P('CPA · 行动','CPA · actions'),P('按已定义行动付费：发布方承担更多行动风险。但行动质量、归因和后续利润仍须核验。','Pay per defined action: publisher bears more action risk. Action quality, attribution and downstream profit still require validation.'),2)]},
 targeting:{kind:'signals',label:P('定向信号 ≠ 个性化粒度','Targeting signal ≠ personalization granularity'),note:P('四类按第 20–21 页概念整理，可联合使用，不是互斥四象限。分群／逐人是另一个粒度维度，越细不自动越有效。','Four signal types from pp.20–21 may combine; not mutually exclusive quadrants. Segment/individual tailoring is a separate dimension; finer is not automatically better.'),nodes:[
 N(26,22,P('语境 · 内容','Context · content'),P('根据页面主题、内容或任务线索定向；课件说明也可结合关键词。','Target from page themes/content or task cues; the slide also allows keywords.'),0),
 N(74,22,P('行为 · 搜索与点击','Behavior · search/clicks'),P('根据历史搜索与点击等行为，不应把行为直接等同于购买意图。','Use past searches/clicks; observed behavior is not purchase intent.'),1),
 N(26,52,P('再营销 · 本品牌接触','Retarget · brand contact'),P('向曾接触本品牌的人再次沟通；接触事实与是否新增购买是两回事。','Contact previous brand visitors again; contact history and incremental buying are different claims.'),2),
 N(74,52,P('地理 · 位置','Geographic · location'),P('按位置或区域沟通；信号可用性、权限和成本仍需核实。','Communicate by location/area; inspect signal availability, permission and cost.'),3),
 N(50,85,P('粒度：分群 ↔ 逐人','Granularity: segment ↔ individual'),P('第 14、18 页区分分群和逐人个性化。它们是信息应用的粒度，不是第五种数据来源；逐人通常需要更多资源。','Pages 14/18 distinguish segment and individual tailoring. This is application granularity, not a fifth data source; individual tailoring requires more resources.'),4)]},
 recommender:{kind:'method-choice',label:P('可用信息 → 推荐候选 → 同条件比较','Available information → candidates → fair comparison'),note:P('根据第 5–12 页的机制与优劣整理候选入口；选择条件属于教学综合，不是课件中的最优规则。第 12 页的元路径仅是混合的一个实现。箭头不表示候选效果已成立。','Candidate entry points synthesized from mechanisms/trade-offs on pp.5–12; conditions are editorial, not a slide optimality rule. Meta-paths on p.12 are one hybrid implementation; arrows do not establish effectiveness.'),nodes:[
 N(50,13,P('先查可用信息','Check available information'),P('先区分物品属性、兴趣锚点和用户／物品互动，再定义评价目标。信息只能支持提出候选，不能直接选出赢家。','Distinguish attributes, interest anchors and user/item interactions, then define the evaluation goal. Information supports candidates, not an automatic winner.')),
 N(18,48,P('内容推荐','Content-based'),P('第 6、8 页：依据物品属性与相似性。教学选择入口：有属性和种子物品／兴趣锚点时可测试；缺少用户历史也不等于可凭空个性化。相似性可能不匹配真实偏好。','Pages 6/8: use item attributes/similarity. Editorial entry: test when attributes and a seed/interest anchor are usable; no user history does not mean personalization from nothing. Similarity may miss actual preferences.'),0),
 N(50,48,P('协同过滤','Collaborative'),P('第 9–10 页：根据相似用户的行为推荐。教学选择入口：有可比互动时可测试；稀疏、新用户和新商品是限制，不能只因数据量大就保证适用。','Pages 9–10: recommend from similar-user behavior. Editorial entry: test with comparable interactions; sparsity, new users/items constrain it. Large total datasets do not guarantee suitability.'),1),
 N(82,48,P('混合推荐','Hybrid'),P('第 11–12 页给出混合／元路径例子。教学选择入口：信息互补且有能力实现和验证时可评估混合；不是“信息都汇合就更好”。具体元路径例子见下方。','Pages 11–12 present hybrid/meta-path examples. Editorial entry: evaluate hybrids when information is complementary and implementation/validation are feasible; fusion alone does not imply improvement. See the specific meta-path example below.'),2)]},
 attribution:{kind:'credit',label:P('同一路径，不同信用分配','Same path, different credit'),note:P('假设已转化路径；分配总和为 100%，但信用不是因果贡献或销售增量。','Hypothetical converted path: allocated credit sums to 100%, not causal contribution or lift.'),nodes:[
 N(20,35,P('社交','Social'),P('首次点击规则将全部信用分给起点，不代表其真实因果贡献。','First-click assigns all credit to the start, not its true causal effect.'),0),
 N(50,35,P('邮件','Email'),P('中间触点可能辅助转化；末次规则不给信用不表示它没有作用。','A middle touch may assist; zero last-click credit is not no effect.'),0),
 N(80,35,P('搜索','Search'),P('末次点击给收尾触点全部信用，不能由此排除前面触点的价值。','Last-click credits the closing touch without ruling out earlier value.'),0)]},
 mmm:{kind:'model-fit',label:P('用实际 Y 拟合，不是凭投入生成销售','Fit observed Y, not sales from spend alone'),note:P('左侧包括建模所需的历史结果 Y 和解释变量 X；Y 用于拟合，不是控制变量。右侧拟合／估计不等于实际观测或因果增量。预算判断须经过下方应用检查。','Left: observed historical Y and explanatory X for estimation; Y is used for fitting, not as a control. Right: fit/estimates are not observations or causal lift. Budget interpretation must pass the application checks below.'),nodes:[
 N(17,20,P('实际销售 Y','Observed sales Y'),P('第 9 页把销售等列为结果变量。先有实际历史 Y，模型才有要拟合的结果；不能只凭广告投入估计销售贡献。','Page 9 lists sales as an outcome variable. Observed historical Y provides the outcome to fit; spend alone cannot estimate sales contribution.'),0),
 N(17,50,P('媒体投入 X','Media inputs X'),P('媒体投入是解释变量：对齐与销售相同的时间粒度，检查是否有可用变化及相互关联。','Media inputs are explanatory variables: align with sales timing and inspect usable variation/dependence.'),1),
 N(17,80,P('促销／季节等 X','Other factors X'),P('其他可测因素参与建模；纳入控制并不保证没有遗漏，也不自动识别因果。','Other measurable factors enter the model; controls do not guarantee no omissions or causal identification.'),2),
 N(53,50,P('拟合 MMM','Fit MMM'),P('用已观测的 Y 与 X 估计模型关系；设定、滞后及遗漏影响结果。没有实际结果或关键变化不足，应暂停。','Estimate relationships using observed Y/X; specification, lags and omissions matter. Pause without outcomes or usable variation.'),3),
 N(85,50,P('拟合／估计','Fit / estimates'),P('报告拟合值、关系估计和不确定性，不能把拟合好当成因果有效。预算建议还需对假设和其他证据作核验。','Report fit, relationship estimates and uncertainty; good fit is not causal validity. Budget advice also requires checked assumptions and other evidence.'),3)]},
 regression:{kind:'branch',label:P('由 Y 的尺度选择模型','Choose a model from Y'),note:P('课程模型选择入口，不是对所有连续／二元数据的适用保证；诊断与假设仍需检查。','Course model entry point, not universal suitability; inspect assumptions and diagnostics.'),nodes:[
 N(50,14,P('结果变量 Y','Outcome Y'),P('先定义业务结果及测量尺度，再选择模型。','Define the outcome and scale before choosing the model.')),
 N(25,45,P('连续金额／数量','Continuous outcome'),P('例如金额；模型设定与误差假设仍需检查。','For example, spending; inspect specification and error assumptions.'),0),
 N(75,45,P('二元 0／1','Binary 0 / 1'),P('例如购买或未购买，概率须在 0 与 1 之间。','For example purchase/no purchase, with probabilities between 0 and 1.'),1),
 N(25,79,P('线性回归','Linear regression'),P('系数与 Y 单位相关；显著不是因果或业务重要性的证明。','Coefficients depend on Y units; significance is not causality or importance.'),0),
 N(75,79,P('逻辑回归','Logistic regression'),P('OR 是优势比，不是概率倍数或百分点变化。','An odds ratio is not a probability ratio or percentage-point change.'),3)]},
 experiment:{kind:'experiment-split',label:P('随机分组，再比较同一个结果','Randomize, then compare the same outcome'),note:P('整理第 16–17 页的随机分组比较结构。随机分配不等于随机抽样；比较广告 A/B 也不等于检验有广告／无广告的增量。','Organizes random-assignment comparison on pp.16–17. Assignment is not random sampling; ad A/B comparison is not ads-versus-no-ads lift.'),nodes:[
 N(50,11,P('随机分配','Random assignment'),P('先确定问题、实验单位和对照，再随机分配；这样有助于平衡混淆因素，但不保证样本代表所有顾客。','Define question, units and control, then randomize. Assignment helps balance confounders but does not guarantee population representativeness.'),1),
 N(25,39,P('A · 条件一','A · condition 1'),P('明确 A 接受的内容、时间与处理条件。若问题是广告增量，需恰当的无广告对照，而非仅换文案。','Specify A’s content, timing and treatment. Ad-lift questions need an appropriate no-ad control, not merely different copy.'),1),
 N(75,39,P('B · 条件二','B · condition 2'),P('明确 B 与 A 的差别，尽量避免同时改变多个无法拆分的因素。','Specify how B differs from A; avoid bundled changes whose effects cannot be separated.'),1),
 N(25,65,P('A 的结果','A outcomes'),P('使用预先定义的业务结果、分母和时间窗口，并检查脱落或组间干扰。','Use predefined outcomes, denominators and windows; inspect attrition and interference.'),2),
 N(75,65,P('B 的结果','B outcomes'),P('使用与 A 一致的测量方式，不能把不同窗口或不同分母直接比较。','Measure consistently with A; do not compare incompatible windows or denominators.'),2),
 N(50,91,P('差异＋不确定性','Difference + uncertainty'),P('比较效果大小和不确定性，再权衡成本与外推边界。显著不自动等于业务重要。','Compare effect size/uncertainty, then costs and generalizability. Statistical significance is not automatically business importance.'),2)]}
};
const provenance={source:P('课件结构重绘','Slide-structure redraw'),concept:P('课件概念整理','Slide-concept map'),example:P('假设示例','Hypothetical example'),template:P('应用空白模板','Blank application template')};
const sourceMap={race:['source','w1',34,34],media:['concept','w1',13,16],journey:['example','w2',3,7],'brand-identity':['source','w2',27,27],'emotion-wheel':['source','w3',8,8],'automation-augmentation':['concept','genai',7,7],influence:['example','w2',28,29],'topic-journey':['template','w3',10,11],'search-mix':['source','w4',51,51],'ad-pricing':['concept','w5',3,9],targeting:['concept','w5',14,21],recommender:['concept','w6',5,12],attribution:['example','w1',43,58],mmm:['concept','w2',8,10],regression:['concept','t1',10,35],experiment:['concept','w5',16,17]};
for(const [id,[basis,source,start,end]] of Object.entries(sourceMap)){Object.assign(diagrams[id],{basis,sourceRefs:[{id:source,pages:[start,end]}]})}
diagrams.mmm.nodes.forEach((n,i)=>n.dataRole=['observed-outcome','explanatory-media','explanatory-controls','estimation','estimated-output'][i]);
diagrams.recommender.nodes.forEach((n,i)=>n.dataRole=['available-information','content-candidate','collaborative-candidate','hybrid-candidate'][i]);
const intensity=[P('宁静 → 喜悦 → 狂喜','Serenity → joy → ecstasy'),P('接受 → 信任 → 钦佩','Acceptance → trust → admiration'),P('担忧 → 恐惧 → 惊恐','Apprehension → fear → terror'),P('分心 → 惊讶 → 惊愕','Distraction → surprise → amazement'),P('忧思 → 悲伤 → 哀恸','Pensiveness → sadness → grief'),P('无聊 → 厌恶 → 憎恶','Boredom → disgust → loathing'),P('不悦 → 愤怒 → 暴怒','Annoyance → anger → rage'),P('兴趣 → 期待 → 警觉','Interest → anticipation → vigilance')];
const blend=[P('喜悦＋信任＝爱','Joy + trust = love'),P('信任＋恐惧＝顺从','Trust + fear = submission'),P('恐惧＋惊讶＝敬畏','Fear + surprise = awe'),P('惊讶＋悲伤＝不赞同','Surprise + sadness = disapproval'),P('悲伤＋厌恶＝懊悔','Sadness + disgust = remorse'),P('厌恶＋愤怒＝轻蔑','Disgust + anger = contempt'),P('愤怒＋期待＝攻击性','Anger + anticipation = aggressiveness'),P('期待＋喜悦＝乐观','Anticipation + joy = optimism')];
diagrams['emotion-wheel'].nodes.forEach((n,i)=>{n.explain=P(n.explain[0]+' 课件强度由弱到强：'+intensity[i][0]+'；相邻混合示例：'+blend[i][0]+'。这是模型分类，不是对某条评论的自动判定。',n.explain[1]+' Slide intensity, weak to strong: '+intensity[i][1]+'. Adjacent blend: '+blend[i][1]+'. Model categories, not automatic labels for a comment.')});
diagrams['emotion-wheel'].note=P('简化重绘八类与对立关系；点击节点查看课件中的强度和相邻混合情绪。完整轮见原课件第 8 页；配色不是强度数据。','Simplifies eight categories/opposites. Select nodes for slide intensities and adjacent blends; see p.8 for the full wheel. Colors are not intensity data.');
const colors=['#2662d9','#0b897d','#b77812','#7755bd'];
let serial=0;
function nodeHTML(n,i,f,mini,kind){const tag=mini?'span':'button',attrs=mini?'':` type="button" data-fv-node="${i}" aria-pressed="${i===0}"`;return `<${tag}${attrs}${n.dataRole?` data-fv-role="${n.dataRole}"`:''} class="fv-node fv-node-${i}${i===0&&!mini?' is-selected':''}" style="left:${n.x}%;top:${n.y}%">${bi(n.label,'span','bi')}</${tag}>`}
function shape(d,uid){
const path=(s,extra='')=>`<path d="${s}" class="fv-line" ${extra}/>`;
const line=(a,b,arrow=true,dash=false)=>path(`M${a[0]} ${a[1]} L${b[0]} ${b[1]}`,`${arrow?`marker-end="url(#${uid})"`:''}${dash?' stroke-dasharray="5 6"':''}`);
const rect=(x,y,w,h,c,opacity=.1)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="14" fill="${c}" fill-opacity="${opacity}"/>`;
let marks='';
if(d.kind==='race-plan'){for(let i=0;i<4;i++){const y=85+i*65,a=95+i*24,b=507-i*24;marks+=`<path d="M${a} ${y} H${b} L${b-20} ${y+52} H${a+20} Z" fill="${colors[i]}" fill-opacity=".13"/>`;}marks+=path('M450 306 H556 Q575 306 575 280 V51 Q575 36 551 36 H461',`stroke-dasharray="5 6" marker-end="url(#${uid})"`)}
if(d.kind==='paradox'){marks=rect(26,24,275,145,colors[0],.07)+rect(339,24,275,145,colors[1],.07)+line([260,100],[380,100],false)+path('M160 169 V272 H480 V169','stroke-dasharray="5 6"')}
if(d.kind==='time-effects'){marks=line([45,302],[610,302])+line([45,302],[45,32])+path('M54 287 C68 248 85 101 166 87 C229 79 253 184 319 267 C359 302 485 292 597 294','style="stroke:#b77812;stroke-width:3.5"')+path('M54 294 C197 293 241 261 297 210 C365 142 460 87 597 78','style="stroke:#0b897d;stroke-width:3.5"')}
if(d.kind==='pricing-compare'){for(let i=0;i<3;i++)marks+=rect(22+i*205,25,186,284,colors[i],.08)}
if(d.kind==='signals'){for(const n of d.nodes.slice(0,4))marks+=rect(n.x*6.4-125,n.y*3.6-40,250,80,colors[0],.06);marks+=rect(76,272,488,66,colors[1],.08)}
if(d.kind==='model-fit'){marks=line([190,72],[253,162])+line([190,180],[253,180])+line([190,288],[253,198])+line([422,180],[460,180])}
if(d.kind==='method-choice'){marks=path('M320 73 V119 H115 V143',`marker-end="url(#${uid})"`)+line([320,119],[320,143])+path('M320 119 H525 V143',`marker-end="url(#${uid})"`);for(let i=0;i<3;i++)marks+=rect(24+i*205,135,180,177,colors[i],.065)}
if(d.kind==='experiment-split'){marks=path('M320 59 V92 H160 V112',`marker-end="url(#${uid})"`)+path('M320 92 H480 V112',`marker-end="url(#${uid})"`)+line([160,168],[160,207])+line([480,168],[480,207])+path('M160 261 V287 H320 V301',`marker-end="url(#${uid})"`)+path('M480 261 V287 H320','')}
if(d.kind==='hub'){marks='<circle cx="320" cy="180" r="50" class="fv-core-ring"/>';for(const n of d.nodes)marks+=line([320,180],[n.x*6.4,n.y*3.6],false)}
if(d.kind==='brand'){for(let row=0;row<3;row++)marks+=rect(22,row*108+20,596,104,colors[row],.07);for(let i=0;i<9;i++){if(i!==4)marks+=line([320,180],[d.nodes[i].x*6.4,d.nodes[i].y*3.6],false)}}
if(d.kind==='wheel'){for(let i=0;i<8;i++){const a=(i*45-112.5)*Math.PI/180,b=a+Math.PI/4;marks+=`<path d="M320 180 L${320+275*Math.cos(a)} ${180+157*Math.sin(a)} A275 157 0 0 1 ${320+275*Math.cos(b)} ${180+157*Math.sin(b)} Z" fill="${colors[i%4]}" fill-opacity=".14"/>`;}marks+='<ellipse cx="320" cy="180" rx="83" ry="50" fill="#ffffff"/>';for(let i=0;i<4;i++)marks+=line([d.nodes[i].x*6.4,d.nodes[i].y*3.6],[d.nodes[i+4].x*6.4,d.nodes[i+4].y*3.6],false,true)}
if(d.kind==='lanes'){for(let i=0;i<3;i++)marks+=rect(10,i*100+30,620,98,colors[i],.06);marks+=path('M175 84 C238 84 235 180 307 180',`marker-end="url(#${uid})"`)+path('M340 180 C420 180 420 281 482 281',`marker-end="url(#${uid})"`)+path('M510 257 C574 220 574 130 518 95',`marker-end="url(#${uid})"`)+path('M178 99 Q280 290 457 278',`stroke-dasharray="5 6" marker-end="url(#${uid})"`)}
if(d.kind==='network'){const edges=[[0,1],[0,2],[0,3],[1,4],[1,5],[2,5],[3,5],[3,6]];for(const[a,b]of edges)marks+=line([d.nodes[a].x*6.4,d.nodes[a].y*3.6],[d.nodes[b].x*6.4,d.nodes[b].y*3.6]);for(const n of d.nodes)marks+=`<circle cx="${n.x*6.4}" cy="${n.y*3.6}" r="35" class="fv-network-circle"/>`}
if(d.kind==='cross'){for(const n of d.nodes)marks+=rect(n.x*6.4-72,n.y*3.6-45,144,90,colors[0],.055);marks+=path('M111 65 H619 M111 187 H619', 'style="stroke:#d9e3ee"')}
if(d.kind==='credit'){marks=line([179,126],[265,126])+line([371,126],[457,126])}
if(d.kind==='branch'){marks=path('M320 72 V111 H160 V137',`marker-end="url(#${uid})"`)+path('M320 111 H480 V137',`marker-end="url(#${uid})"`)+line([160,193],[160,253])+line([480,193],[480,253])}
return `<svg class="fv-drawing" viewBox="0 0 640 360" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="${uid}" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M1 1 L9 5 L1 9" fill="none" stroke="#7186a6" stroke-width="1.8"/></marker></defs>${marks}</svg>`;
}
function credits(mini){return `<div class="fv-credits">${[0,0,100].map((v,i)=>`<div><span class="fv-credit-value" data-fv-credit-value="${i}">${v}%</span><span class="fv-credit-track"><span data-fv-credit-bar="${i}" style="width:${v}%"></span></span></div>`).join('')}</div>${mini?'':`<div class="fv-rules" role="group" aria-label="归因规则 / Attribution rule">${[['first',P('首次点击','First-click')],['last',P('末次点击','Last-click')],['linear',P('线性均分','Linear')]].map(([id,p])=>`<button type="button" data-fv-rule="${id}" aria-pressed="${id==='last'}">${bi(p,'span','bi')}</button>`).join('')}</div>`}`}
function badge(f){return bi(provenance[diagrams[f.id].basis],'span','fv-provenance bi')}
function diagram(f,mini=false){
 const d=diagrams[f.id],uid='fv-arrow-'+(++serial);
 const sources=d.sourceRefs.map(r=>`<button type="button" class="pdf-button compact" data-pdf="${esc(r.id)}" data-page="${r.pages[0]}" data-end="${r.pages[1]}">${bi(P(`核对原课件 · PDF ${r.pages[0]}${r.pages[1]===r.pages[0]?'':'–'+r.pages[1]}`,`Check slides · PDF ${r.pages[0]}${r.pages[1]===r.pages[0]?'':'–'+r.pages[1]}`),'span','bi')} ↗</button>`).join('');
 let labels='';
 if(d.kind==='race-plan')labels+=bi(P('回看计划','Revisit plan'),'span','fv-return bi');
 if(d.kind==='paradox')labels+=`<span class="fv-human" style="left:25%">${bi(P('人 → 机器','Human → machine'),'span','bi')}</span><span class="fv-human" style="left:75%">${bi(P('人 ↔ 机器','Human ↔ machine'),'span','bi')}</span>`;
 if(d.kind==='method-choice')labels+=[P('属性＋兴趣锚点','Attributes + interest anchor'),P('可比的互动记录','Comparable interactions'),P('互补信息＋实现能力','Complementary information + implementation')].map((p,i)=>`<div class="fv-choice-cue" style="left:${18+i*32}%">${bi(p,'span','bi')}</div>`).join('');
 if(d.kind==='pricing-compare')labels+=[P('每千次展示','Per 1,000 impressions'),P('每次点击','Per click'),P('每次定义行动','Per defined action')].map((p,i)=>`<div class="fv-price-event" style="left:${18+i*32}%">${bi(p,'strong','bi')}${bi([P('广告主承担后续点击／行动风险','Advertiser bears downstream click/action risk'),P('广告主承担点击后行动风险','Advertiser bears post-click action risk'),P('发布方承担更多行动风险','Publisher bears more action risk')][i],'span','bi')}</div>`).join('');
 return `<div class="fv${mini?' fv-mini':''} fv-${d.kind}" data-fv="${f.id}" data-fv-basis="${d.basis}"${mini?'':` role="group" aria-label="${esc(d.label.join(' / '))}"`}>${mini?'':`<div class="fv-heading">${bi(d.label,'strong','bi')}${badge(f)}</div><div class="fv-source-bar">${bi(P('点节点理解关系；点课件核对原文','Select a node; open the slides to check the source'),'span','bi')}${sources}</div>`}<div class="fv-board">${shape(d,uid)}${d.center?bi(d.center,'div','fv-center bi'):''}${d.axes?`<div class="fv-axis fv-axis-x">${bi((mini?d.miniAxes:d.axes)[0],'span','bi')}</div><div class="fv-axis fv-axis-y">${bi((mini?d.miniAxes:d.axes)[1],'span','bi')}</div>`:''}${d.lanes?d.lanes.map((p,i)=>`<span class="fv-lane" style="top:${22+i*28}%">${bi(p,'span','bi')}</span>`).join(''):''}${d.kind==='brand'?`<span class="fv-band" style="top:2%">${bi(P('外部','External'),'span','bi')}</span><span class="fv-band" style="top:32%">${bi(P('连接','Bridge'),'span','bi')}</span><span class="fv-band" style="top:62%">${bi(P('内部','Internal'),'span','bi')}</span>`:''}${d.rows?d.rows.map((p,i)=>`<span class="fv-row-label" style="top:${34+i*38}%">${bi(p,'span','bi')}</span>`).join('')+d.cols.map((p,i)=>`<span class="fv-col-label" style="left:${30+i*27}%">${bi(p,'span','bi')}</span>`).join(''):''}${labels}${d.nodes.map((n,i)=>nodeHTML(n,i,f,mini,d.kind)).join('')}${d.kind==='credit'?credits(mini):''}</div>${mini?'':`<div class="fv-inspect" aria-live="polite">${bi(d.nodes[0].explain,'p','bi')}</div>${bi(d.note,'p','fv-caption bi')}`}</div>`
}
function click(e){const node=e.target.closest('[data-fv-node]'),rule=e.target.closest('[data-fv-rule]');if(node){const root=node.closest('[data-fv]'),d=diagrams[root.dataset.fv],n=d.nodes[Number(node.dataset.fvNode)];root.querySelectorAll('[data-fv-node]').forEach(b=>{const active=b===node;b.setAttribute('aria-pressed',active);b.classList.toggle('is-selected',active)});root.querySelector('.fv-inspect').innerHTML=bi(n.explain,'p','bi')}
 if(rule){const root=rule.closest('[data-fv]'),values={first:[100,0,0],last:[0,0,100],linear:[100/3,100/3,100/3]}[rule.dataset.fvRule];root.querySelectorAll('[data-fv-rule]').forEach(b=>b.setAttribute('aria-pressed',b===rule));values.forEach((v,i)=>{root.querySelector(`[data-fv-credit-bar="${i}"]`).style.width=v+'%';root.querySelector(`[data-fv-credit-value="${i}"]`).textContent=Number.isInteger(v)?v+'%':v.toFixed(1)+'%'});root.querySelector('.fv-inspect').innerHTML=bi(rule.dataset.fvRule==='linear'?P('线性规则让三个触点各得 1/3 信用。只是规则均分，不证明真实贡献相同。','Linear allocation gives each touch one third. Equal rule credit does not establish equal true contribution.'):rule.dataset.fvRule==='first'?P('首次点击：社交得到全部信用。规则强调引入角色，但不能推出社交产生全部增量。','First-click: all credit to social. Emphasizing introduction does not establish all incremental value.'):P('末次点击：搜索得到全部信用。规则强调收尾，不能推出前面的触点没有价值。','Last-click: all credit to search. Emphasizing closure does not establish that earlier touches have no value.'),'p','bi')}
}
return {diagram,badge,click,descriptions:diagrams};
}};
